#include "../src/gameplay_program.h"
#include <cassert>
#include <iostream>
int main() {
  const nlohmann::json definition = nlohmann::json::parse(R"({"flags":[{"id":"doorOpen","type":"boolean","initial":false},{"id":"keys","type":"number","initial":0}],"events":[{"id":"doorOpened"}],"sequences":[{"id":"unlock","steps":[{"type":"action","action":{"type":"incrementFlag","flag":"keys","amount":1}},{"type":"parallel","steps":[{"type":"action","action":{"type":"setFlag","flag":"doorOpen","value":true}},{"type":"serial","steps":[{"type":"wait","ticks":2},{"type":"action","action":{"type":"emitEvent","event":"doorOpened"}}]}]}]}]})");
  GameplayProgram state(definition); std::string emitted; state.SetEventSink([&emitted](const std::string& event) { emitted = event; }); state.StartSequence("unlock"); state.StepSequences(); assert(state.Flag("keys") == 1); assert(state.Flag("doorOpen") == true); assert(!state.HasEvent("doorOpened")); state.BeginTick(); state.StepSequences(); assert(!state.HasEvent("doorOpened")); state.BeginTick(); state.StepSequences(); assert(state.HasEvent("doorOpened")); assert(emitted == "doorOpened"); state.BeginTick(); assert(!state.HasEvent("doorOpened")); state.Reset(); assert(state.Flag("keys") == 0); assert(state.Flag("doorOpen") == false);
  state.ValidateTrigger(nlohmann::json::parse(R"({"conditions":[{"type":"flag","flag":"keys","comparison":"equal","value":0}],"actions":[{"type":"setFlag","flag":"doorOpen","value":true}],"sequence":"unlock"})"));
  nlohmann::json registered; state.SetActionSink([&registered](const nlohmann::json& action) { registered = action; }); state.Execute(nlohmann::json::parse(R"({"type":"setEntityVisible","entityType":"backgroundObject","id":7,"visible":true,"restartAnimation":true})")); assert(registered.at("id") == 7);
  state.Execute(nlohmann::json::parse(R"({"type":"setPlayerMode","visible":false,"controllable":false})")); assert(registered.at("type") == "setPlayerMode");
  state.Execute(nlohmann::json::parse(R"({"type":"forcePlayerState","state":"falling","previousState":"walking"})")); assert(registered.at("state") == "falling");
  state.Execute(nlohmann::json::parse(R"({"type":"keepPlayerMoving"})")); assert(registered.at("type") == "keepPlayerMoving");
  state.Execute(nlohmann::json::parse(R"({"type":"setEnemyActive","id":7,"active":false,"reset":true})")); assert(registered.at("id") == 7 && registered.at("reset") == true);
  bool rejected = false; try { GameplayProgram invalid(nlohmann::json::parse(R"({"flags":[{"id":"ready","type":"boolean","initial":false}],"sequences":[{"id":"bad","steps":[{"type":"action","action":{"type":"incrementFlag","flag":"ready","amount":1}}]}]})")); } catch (...) { rejected = true; } assert(rejected);

  const nlohmann::json scene_definition = nlohmann::json::parse(R"({"sequences":[{"id":"scene","steps":[{"type":"parallel","steps":[{"type":"serial","steps":[{"type":"action","action":{"type":"setEntityVisible","entityType":"backgroundObject","id":2,"visible":true,"restartAnimation":true}},{"type":"wait","ticks":2},{"type":"action","action":{"type":"setEntityVisible","entityType":"backgroundObject","id":2,"visible":false}}]},{"type":"serial","steps":[{"type":"action","action":{"type":"setEntityVisible","entityType":"backgroundObject","id":3,"visible":true,"restartAnimation":true}},{"type":"wait","ticks":4},{"type":"action","action":{"type":"setEntityVisible","entityType":"backgroundObject","id":3,"visible":false}}]}]},{"type":"serial","steps":[{"type":"action","action":{"type":"setEntityVisible","entityType":"backgroundObject","id":0,"visible":true,"restartAnimation":true}},{"type":"wait","ticks":3},{"type":"action","action":{"type":"setEntityVisible","entityType":"backgroundObject","id":0,"visible":false}}]}]}]})");
  GameplayProgram scene(scene_definition); std::vector<std::string> trace; int scene_tick = 0;
  scene.SetActionSink([&trace, &scene_tick](const nlohmann::json& action) { trace.push_back(std::to_string(scene_tick) + ":" + std::to_string(action.at("id").get<int>()) + (action.at("visible").get<bool>() ? ":on" : ":off") + (action.value("restartAnimation", false) ? ":restart" : "")); });
  const std::vector<std::string> expected = {"0:2:on:restart", "0:3:on:restart", "2:2:off", "4:3:off", "4:0:on:restart", "7:0:off"};
  const auto run_scene = [&scene, &scene_tick]() { scene.StartSequence("scene"); for (scene_tick = 0; scene_tick < 20; ++scene_tick) scene.StepSequences(); };
  run_scene(); assert(trace == expected); scene.Reset(); trace.clear(); run_scene(); assert(trace == expected);
  std::cout << "gameplay program ok\n";
}
