import { rickCharacterForms, type CharacterFormDefinition, type CharacterFormsDefinition } from "./character-forms";
import type { CharacterStateDefinition, StateAction, StateCondition, StateTransitionDefinition } from "./character-state-machine";
import type { EditableLevel } from "./level-document";
import { playerActionBindings, runtimeProfileBindings, type PlayerAnimationState, type RuntimeProfileBindingOverrides } from "./platformer-core";
import { BUILT_IN_CHARACTER_EVENTS, engineEvent } from "./engine-events";

const BEHAVIORS = ["stop", "running", "jumping", "crouching", "climbing", "shooting", "bombing", "hitting", "dead"];
const BEHAVIOR_HELP: Record<string, { title: string; effect: string }> = {
  stop: { title: "Built-in locomotion", effect: "Stops horizontal movement while preserving the current facing direction." },
  running: { title: "Built-in locomotion", effect: "Moves left or right using the form's run speed." },
  jumping: { title: "Built-in locomotion", effect: "Applies jumping, falling, gravity and airborne horizontal control." },
  crouching: { title: "Built-in locomotion", effect: "Uses the shorter crouching collision box and permits crouched movement." },
  climbing: { title: "Built-in locomotion", effect: "Aligns the character to stairs and applies vertical climbing movement." },
  shooting: { title: "Built-in action", effect: "Creates one projectile on entry and plays the configured shot sound." },
  bombing: { title: "Built-in action", effect: "Creates one bomb on entry; horizontal input determines its initial movement." },
  hitting: { title: "Built-in action", effect: "Performs Rick's close interaction/hit and can activate a checkpoint." },
  dead: { title: "Built-in lifecycle", effect: "Runs the death movement and applies the configured respawn rules." },
};
const select = (values: readonly string[], value: string): HTMLSelectElement => { const element = document.createElement("select"); for (const item of values) element.add(new Option(item, item)); element.value = value; return element; };
const input = (value: string): HTMLInputElement => { const element = document.createElement("input"); element.value = value; return element; };
const button = (label: string): HTMLButtonElement => { const element = document.createElement("button"); element.type = "button"; element.textContent = label; return element; };
const profile = (level: EditableLevel): Record<string, unknown> => { const current = level.runtimeProfile; if (current && typeof current === "object" && !Array.isArray(current)) return current as Record<string, unknown>; return level.runtimeProfile = {}; };

export class CharacterStateEditor {
  #level: EditableLevel | null = null; #forms: CharacterFormsDefinition | null = null; #form = 0; #state = 0; #onChange: (message: string) => void = () => undefined; #active: () => { form?: string; state?: string } = () => ({});
  #nodePositions = new Map<string, { x: number; y: number }>();
  #lastActive = "";
  #propertyHost: HTMLElement | null = null;
  constructor(readonly controls: HTMLElement, readonly inspector: HTMLElement, readonly graph: HTMLElement) {}
  bind(level: EditableLevel, onChange: (message: string) => void, active: () => { form?: string; state?: string }): void { this.#level = level; this.#onChange = onChange; this.#active = active; const value = profile(level).characterForms; this.#forms = value && typeof value === "object" ? value as CharacterFormsDefinition : null; this.#form = 0; this.#state = 0; this.render(); }
  show(): void { this.controls.hidden = false; this.graph.hidden = false; this.render(); }
  hide(): void { this.controls.hidden = true; this.graph.hidden = true; }
  refreshRuntime(): void { const active = this.#active(), key = `${active.form ?? ""}:${active.state ?? ""}`; if (!this.graph.hidden && key !== this.#lastActive) { this.#lastActive = key; this.#renderGraph(); } }
  #commit(message: string): void { this.#onChange(message); this.render(); }
  #currentForm(): CharacterFormDefinition | null { return this.#forms?.forms[this.#form] ?? null; }
  #currentState(): CharacterStateDefinition | null { return this.#currentForm()?.stateMachine.states[this.#state] ?? null; }
  render(): void {
    this.controls.innerHTML = ""; this.inspector.innerHTML = ""; this.inspector.classList.remove("empty-inspector");
    if (!this.#level) return;
    if (!this.#forms) { const help = document.createElement("p"); help.className = "profile-help"; help.textContent = "This level uses the implicit Rick state machine."; const materialize = button("Create Rick state machine"); materialize.className = "primary"; materialize.onclick = () => { const root = profile(this.#level!); root.characterForms = rickCharacterForms(root.controller as never, root.capabilities as never, root.actionBindings as never); this.#forms = root.characterForms as CharacterFormsDefinition; this.#commit("Rick state machine created"); }; this.controls.append(help, materialize); this.inspector.innerHTML = "<h3>Character states</h3><p class=profile-help>Materialize the compatibility profile to edit forms, states and transitions.</p>"; this.#renderGraph(); return; }
    const formSelect = select(this.#forms.forms.map((form) => form.id), this.#currentForm()?.id ?? ""); formSelect.onchange = () => { this.#form = Math.max(0, this.#forms!.forms.findIndex((form) => form.id === formSelect.value)); this.#state = 0; this.render(); };
    const formActions = document.createElement("div"); formActions.className = "paired-actions"; const addForm = button("+ Form"), deleteForm = button("− Form"); deleteForm.disabled = this.#forms.forms.length <= 1; addForm.onclick = () => { const id = this.#unique("form", this.#forms!.forms.map((form) => form.id)); this.#forms!.forms.push({ id, stateMachine: { initialState: "idle", states: [{ id: "idle", behavior: "stop", transitions: [] }] } }); this.#form = this.#forms!.forms.length - 1; this.#state = 0; this.#commit("Character form added"); }; deleteForm.onclick = () => { const removed = this.#forms!.forms.splice(this.#form, 1)[0]!; for (const form of this.#forms!.forms) for (const state of form.stateMachine.states) for (const transition of state.transitions) transition.actions = transition.actions?.filter((action) => action.type !== "setForm" || action.form !== removed.id); if (this.#forms!.initialForm === removed.id) this.#forms!.initialForm = this.#forms!.forms[0]!.id; this.#form = 0; this.#state = 0; this.#commit("Character form deleted"); }; formActions.append(addForm, deleteForm);
    const stateList = document.createElement("div"); stateList.className = "state-list"; this.#currentForm()!.stateMachine.states.forEach((state, index) => { const item = button(state.id); item.classList.toggle("selected", index === this.#state); item.onclick = () => { this.#state = index; this.render(); }; stateList.append(item); });
    const stateActions = document.createElement("div"); stateActions.className = "paired-actions"; const addState = button("+ State"), deleteState = button("− State"); deleteState.disabled = this.#currentForm()!.stateMachine.states.length <= 1; addState.onclick = () => { const form = this.#currentForm()!, id = this.#unique("state", form.stateMachine.states.map((state) => state.id)); form.stateMachine.states.push({ id, behavior: "stop", transitions: [] }); this.#state = form.stateMachine.states.length - 1; this.#commit("Character state added"); }; deleteState.onclick = () => { const form = this.#currentForm()!, removed = form.stateMachine.states.splice(this.#state, 1)[0]!; for (const state of form.stateMachine.states) state.transitions = state.transitions.filter((transition) => transition.to !== removed.id); if (form.stateMachine.initialState === removed.id) form.stateMachine.initialState = form.stateMachine.states[0]!.id; this.#state = 0; this.#commit("Character state deleted"); }; stateActions.append(addState, deleteState);
    this.controls.append(formSelect, formActions, stateList, stateActions); this.#renderInspector(); this.#renderGraph();
  }
  #renderInspector(): void {
    const form = this.#currentForm()!, state = this.#currentState()!;
    const intro = document.createElement("div"); intro.className = "state-inspector-intro"; intro.innerHTML = `<strong>${state.id}</strong><span>State in character form <b>${form.id}</b></span>`; this.inspector.append(intro);
    const formSection = this.#section("Character form", "Which character configuration owns this state."); this.inspector.append(formSection); this.#propertyHost = formSection;
    this.#field("Form ID", form.id, (value) => { const old = form.id; form.id = value; if (this.#forms!.initialForm === old) this.#forms!.initialForm = value; for (const candidate of this.#forms!.forms) for (const source of candidate.stateMachine.states) for (const transition of source.transitions) for (const action of transition.actions ?? []) if (action.type === "setForm" && action.form === old) action.form = value; }, "Form renamed");
    this.#field("Sprite definition", form.definition ?? "", (value) => form.definition = value || undefined, "Form definition changed");
    const visualScale = document.createElement("label"); visualScale.className = "property-field"; visualScale.append(Object.assign(document.createElement("span"), { textContent: "Visual scale" })); const visualScaleInput = input(form.visualScale === undefined ? "" : String(form.visualScale)); visualScaleInput.type = "number"; visualScaleInput.min = "0"; visualScaleInput.step = "any"; visualScaleInput.placeholder = "1 (implicit)"; visualScaleInput.onchange = () => { const raw = visualScaleInput.value.trim(); if (!raw) delete form.visualScale; else { const value = Number(raw); if (!Number.isFinite(value) || value <= 0) { visualScaleInput.setCustomValidity("Visual scale must be greater than zero"); visualScaleInput.reportValidity(); return; } visualScaleInput.setCustomValidity(""); form.visualScale = value; } this.#commit("Form visual scale changed"); }; visualScale.append(visualScaleInput); formSection.append(visualScale);
    const initialForm = document.createElement("label"); initialForm.className = "property-field checkbox-field"; const initialFormInput = document.createElement("input"); initialFormInput.type = "checkbox"; initialFormInput.checked = this.#forms!.initialForm === form.id; initialFormInput.onchange = () => { if (initialFormInput.checked) { this.#forms!.initialForm = form.id; this.#commit("Initial form changed"); } }; initialForm.append(initialFormInput, document.createTextNode(" Use when the level starts")); formSection.append(initialForm);
    const stateSection = this.#section("Selected state", "What the character does and displays while this state is active."); this.inspector.append(stateSection); this.#propertyHost = stateSection;
    this.#field("State ID", state.id, (value) => { const old = state.id; state.id = value; for (const source of form.stateMachine.states) for (const transition of source.transitions) if (transition.to === old) transition.to = value; if (form.stateMachine.initialState === old) form.stateMachine.initialState = value; }, "State renamed");
    this.#selectField("Movement behavior", BEHAVIORS, state.behavior ?? (BEHAVIORS.includes(state.id) ? state.id : "stop"), (value) => state.behavior = value, "State behavior changed"); this.#field("Animation override (optional)", state.animation ?? "", (value) => state.animation = value || undefined, "State animation changed");
    const initial = document.createElement("label"); initial.className = "property-field checkbox-field"; const initialInput = document.createElement("input"); initialInput.type = "checkbox"; initialInput.checked = form.stateMachine.initialState === state.id; initialInput.onchange = () => { if (initialInput.checked) { form.stateMachine.initialState = state.id; this.#commit("Initial state changed"); } }; initial.append(initialInput, document.createTextNode(" Start this form in this state")); stateSection.append(initial);
    stateSection.append(this.#runtimeInfo(form, state));
    const transitions = this.#section("Outgoing transitions", "Checked from top to bottom. The first matching rule changes the state."); this.inspector.append(transitions); this.#propertyHost = transitions; const add = button("+ Add transition"); add.className = "add-transition"; add.onclick = () => { state.transitions.push({ to: form.stateMachine.states.find((candidate) => candidate !== state)?.id ?? state.id, conditions: [{ type: "signal", signal: "grounded", value: true }] }); this.#commit("State transition added"); }; this.#propertyHost.append(add);
    state.transitions.forEach((transition, index) => this.#transition(transition, index));
    if (!state.transitions.length) { const empty = document.createElement("p"); empty.className = "profile-help"; empty.textContent = "No exit rules: this is a terminal state."; this.#propertyHost.append(empty); } this.#propertyHost = null;
  }
  #section(title: string, help: string): HTMLElement { const section = document.createElement("section"); section.className = "state-property-section"; const heading = document.createElement("h3"); heading.textContent = title; const description = document.createElement("p"); description.textContent = help; section.append(heading, description); return section; }
  #runtimeInfo(form: CharacterFormDefinition, state: CharacterStateDefinition): HTMLElement {
    const behavior = state.behavior ?? (BEHAVIORS.includes(state.id) ? state.id : "stop"), info = BEHAVIOR_HELP[behavior] ?? { title: "Custom behavior", effect: "This behavior must be registered by the game runtime." };
    const root = profile(this.#level!), rawBindings = root.bindings && typeof root.bindings === "object" && !Array.isArray(root.bindings) ? root.bindings as Record<string, unknown> : {}, rawPlayerStates = rawBindings.playerStates && typeof rawBindings.playerStates === "object" && !Array.isArray(rawBindings.playerStates) ? rawBindings.playerStates as Partial<Record<PlayerAnimationState, string>> : {};
    const bindings = runtimeProfileBindings({ playerStates: rawPlayerStates } as RuntimeProfileBindingOverrides), animation = state.animation || bindings.playerStates[behavior as PlayerAnimationState] || "Not mapped";
    const actions = playerActionBindings(form.actionBindings); const controls = Object.entries(actions).filter(([, action]) => action === behavior).map(([direction]) => `Action + ${direction === "horizontal" ? "Left/Right" : direction[0]!.toUpperCase() + direction.slice(1)}`);
    const panel = document.createElement("div"); panel.className = "state-runtime-info"; const heading = document.createElement("div"); heading.className = "runtime-info-heading"; const badge = document.createElement("span"); badge.textContent = info.title; const source = document.createElement("code"); source.textContent = behavior; heading.append(badge, source);
    const effect = document.createElement("p"); effect.textContent = info.effect; const rows = document.createElement("dl"); const add = (label: string, value: string, detail?: string): void => { const row = document.createElement("div"), term = document.createElement("dt"), description = document.createElement("dd"); term.textContent = label; description.textContent = value; if (detail) { const small = document.createElement("small"); small.textContent = detail; description.append(small); } row.append(term, description); rows.append(row); };
    add("Triggered by", controls.length ? controls.join(" or ") : "State transition rules", controls.length ? "Resolved from this form's action bindings" : "No direct action binding targets this behavior"); add("Animation", animation, state.animation ? "Explicit override on this state" : "Resolved from runtimeProfile.bindings.playerStates"); add("Sprite source", form.definition || "Player definition", form.definition ? "Selected by this character form" : "Inherited from the level player"); panel.append(heading, effect, rows); return panel;
  }
  #transition(transition: StateTransitionDefinition, index: number): void {
    const form = this.#currentForm()!, state = this.#currentState()!, card = document.createElement("details"); card.className = "transition-card"; card.open = index === 0;
    const summary = document.createElement("summary"); const priority = document.createElement("span"); priority.className = "transition-priority"; priority.textContent = String(index + 1); const sentence = document.createElement("span"); sentence.innerHTML = `When <b>${this.#conditionSummary(transition.conditions)}</b>, go to <b>${transition.to}</b>`; summary.append(priority, sentence);
    const destinationLabel = document.createElement("label"); destinationLabel.className = "transition-destination"; destinationLabel.append(Object.assign(document.createElement("span"), { textContent: "Go to state" })); const destination = select(form.stateMachine.states.map((item) => item.id), transition.to); destination.onchange = () => { transition.to = destination.value; this.#commit("Transition destination changed"); }; destinationLabel.append(destination);
    const order = document.createElement("div"); order.className = "paired-actions"; const up = button("↑ Higher priority"), down = button("↓ Lower priority"); up.disabled = index === 0; down.disabled = index === state.transitions.length - 1; up.onclick = () => { [state.transitions[index - 1], state.transitions[index]] = [state.transitions[index]!, state.transitions[index - 1]!]; this.#commit("Transition priority changed"); }; down.onclick = () => { [state.transitions[index], state.transitions[index + 1]] = [state.transitions[index + 1]!, state.transitions[index]!]; this.#commit("Transition priority changed"); }; order.append(up, down); card.append(summary, destinationLabel, order);
    const when = document.createElement("h4"); when.textContent = "When all these conditions are true"; card.append(when); transition.conditions.forEach((condition, conditionIndex) => card.append(this.#conditionRow(condition, (next) => { transition.conditions[conditionIndex] = next; this.#commit("Transition condition changed"); }, () => { if (transition.conditions.length > 1) { transition.conditions.splice(conditionIndex, 1); this.#commit("Transition condition deleted"); } })));
    const actions = document.createElement("h4"); actions.textContent = "Then perform these actions"; const addCondition = button("+ Condition"); addCondition.onclick = () => { transition.conditions.push({ type: "signal", signal: "grounded", value: true }); this.#commit("Transition condition added"); }; const addAction = button("+ Action"); addAction.onclick = () => { (transition.actions ??= []).push({ type: "setFacing", value: "input" }); this.#commit("Transition action added"); }; card.append(addCondition, actions); for (const [actionIndex, action] of (transition.actions ?? []).entries()) card.append(this.#actionRow(action, (next) => { transition.actions![actionIndex] = next; this.#commit("Transition action changed"); }, () => { transition.actions!.splice(actionIndex, 1); this.#commit("Transition action deleted"); })); if (!(transition.actions?.length)) { const none = document.createElement("p"); none.className = "transition-none"; none.textContent = "No additional actions"; card.append(none); }
    const remove = button("Delete transition"); remove.className = "danger-action"; remove.onclick = () => { state.transitions.splice(index, 1); this.#commit("Transition deleted"); }; card.append(addAction, remove); (this.#propertyHost ?? this.inspector).append(card);
  }
  #conditionSummary(conditions: StateCondition[]): string { const one = (condition: StateCondition): string => { if (condition.type === "event") return `event “${condition.event}” occurs`; if (condition.type === "control") return `${condition.control} is ${condition.pressed ? "pressed" : "released"}`; if (condition.type === "action") return `${condition.action} is ${condition.active ? "active" : "inactive"}`; if (condition.type === "signal") return `${condition.signal} is ${condition.value}`; if (condition.type === "elapsedTicks") return `time ${condition.comparison} ${condition.value} ticks`; if (condition.type === "distance") return `${condition.axis} distance ${condition.comparison} ${condition.value}`; return `previous state ${condition.comparison} ${condition.state}`; }; return conditions.map(one).join(" and "); }
  #conditionRow(condition: StateCondition, change: (value: StateCondition) => void, remove: () => void): HTMLElement {
    const row = document.createElement("div"); row.className = "rule-row"; const kind = select(["control", "action", "event", "signal", "elapsedTicks", "distance", "previousState"], condition.type);
    const defaults: Record<string, StateCondition> = { control: { type: "control", control: "left", pressed: true }, action: { type: "action", action: "shooting", active: true }, event: { type: "event", event: "landed" }, signal: { type: "signal", signal: "grounded", value: true }, elapsedTicks: { type: "elapsedTicks", comparison: "greaterOrEqual", value: 1 }, distance: { type: "distance", axis: "x", comparison: "greaterOrEqual", value: 8 }, previousState: { type: "previousState", comparison: "equal", state: "stop" } };
    kind.onchange = () => change(defaults[kind.value]!); row.append(kind);
    const boolean = (value: boolean) => select(["true", "false"], String(value));
    const comparisons = ["equal", "notEqual", "greater", "greaterOrEqual", "lower", "lowerOrEqual"];
    if (condition.type === "control") { const name = select(["left", "right", "up", "down", "action"], condition.control), pressed = boolean(condition.pressed); name.onchange = () => change({ ...condition, control: name.value as typeof condition.control }); pressed.onchange = () => change({ ...condition, pressed: pressed.value === "true" }); row.append(name, pressed); }
    else if (condition.type === "action") { const name = input(condition.action), active = boolean(condition.active); name.onchange = () => change({ ...condition, action: name.value }); active.onchange = () => change({ ...condition, active: active.value === "true" }); row.append(name, active); }
    else if (condition.type === "event") { const event = document.createElement("select"); for (const definition of BUILT_IN_CHARACTER_EVENTS) event.add(new Option(`${definition.id} — ${definition.description}`, definition.id)); const gameplay = this.#level?.gameplay as { events?: Array<{ id: string; description?: string }> } | undefined, custom = gameplay?.events?.find((item) => item.id === condition.event); for (const definition of gameplay?.events ?? []) event.add(new Option(`${definition.id} — ${definition.description || "Custom gameplay event"}`, definition.id)); if (!engineEvent(condition.event) && !custom) event.add(new Option(`Unknown event: ${condition.event}`, condition.event)); event.value = condition.event; const emittedWhen = engineEvent(condition.event)?.emittedWhen ?? (custom ? "Emitted by a gameplay action or sequence." : "No runtime emitter is registered for this event"); event.title = emittedWhen; event.onchange = () => change({ ...condition, event: event.value }); row.append(event); const help = document.createElement("span"); help.className = engineEvent(condition.event) || custom ? "event-help" : "event-help event-unknown"; help.textContent = emittedWhen; row.append(help); }
    else if (condition.type === "signal") { const signal = select(["grounded", "onStairs", "canDescendStairs", "canStand", "ceilingBlocked", "descending"], condition.signal), value = boolean(condition.value); signal.onchange = () => change({ ...condition, signal: signal.value as typeof condition.signal }); value.onchange = () => change({ ...condition, value: value.value === "true" }); row.append(signal, value); }
    else if (condition.type === "elapsedTicks") { const comparison = select(comparisons, condition.comparison), value = input(String(condition.value)); value.type = "number"; value.min = "0"; comparison.onchange = () => change({ ...condition, comparison: comparison.value as typeof condition.comparison }); value.onchange = () => change({ ...condition, value: Number(value.value) }); row.append(comparison, value); }
    else if (condition.type === "distance") { const axis = select(["x", "y"], condition.axis), comparison = select(comparisons, condition.comparison), value = input(String(condition.value)); value.type = "number"; value.min = "0"; axis.onchange = () => change({ ...condition, axis: axis.value as "x" | "y" }); comparison.onchange = () => change({ ...condition, comparison: comparison.value as typeof condition.comparison }); value.onchange = () => change({ ...condition, value: Number(value.value) }); row.append(axis, comparison, value); }
    else { const comparison = select(["equal", "notEqual"], condition.comparison), state = select(this.#currentForm()!.stateMachine.states.map((item) => item.id), condition.state); comparison.onchange = () => change({ ...condition, comparison: comparison.value as "equal" | "notEqual" }); state.onchange = () => change({ ...condition, state: state.value }); row.append(comparison, state); }
    const del = button("×"); del.onclick = remove; row.append(del); return row;
  }
  #actionRow(action: StateAction, change: (value: StateAction) => void, remove: () => void): HTMLElement { const row = document.createElement("div"); row.className = "rule-row"; const kind = select(["setFacing", "capturePosition", "setForm"], action.type); let value: HTMLSelectElement; if (action.type === "setFacing") value = select(["input", "left", "right"], action.value); else if (action.type === "capturePosition") value = select(["both", "x", "y"], action.axis); else value = select(this.#forms!.forms.map((form) => form.id), action.form); const apply = () => change(kind.value === "setFacing" ? { type: "setFacing", value: value.value as "left" | "right" | "input" } : kind.value === "capturePosition" ? { type: "capturePosition", axis: value.value as "x" | "y" | "both" } : { type: "setForm", form: value.value }); kind.onchange = () => change(kind.value === "setFacing" ? { type: "setFacing", value: "input" } : kind.value === "capturePosition" ? { type: "capturePosition", axis: "both" } : { type: "setForm", form: this.#forms!.forms[0]!.id }); value.onchange = apply; const del = button("×"); del.onclick = remove; row.append(kind, value, del); return row; }
  #field(labelText: string, value: string, update: (value: string) => void, message: string): void { const label = document.createElement("label"); label.className = "property-field"; label.append(Object.assign(document.createElement("span"), { textContent: labelText })); const control = input(value); control.onchange = () => { if (!control.value.trim() && labelText.includes("ID")) return; update(control.value.trim()); this.#commit(message); }; label.append(control); (this.#propertyHost ?? this.inspector).append(label); }
  #selectField(labelText: string, values: string[], value: string, update: (value: string) => void, message: string): void { const label = document.createElement("label"); label.className = "property-field"; label.append(Object.assign(document.createElement("span"), { textContent: labelText })); const control = select(values, value); control.onchange = () => { update(control.value); this.#commit(message); }; label.append(control); (this.#propertyHost ?? this.inspector).append(label); }
  #renderGraph(): void {
    this.graph.innerHTML = ""; if (!this.#forms) { this.graph.textContent = "Create the Rick state machine to view its graph"; return; }
    const form = this.#currentForm()!, selected = this.#currentState()!, active = this.#active(), graphKey = `${form.id}:`, height = Math.max(440, Math.ceil(form.stateMachine.states.length / 3) * 180);
    const header = document.createElement("header"); header.className = "state-graph-header"; header.innerHTML = `<div><strong>${form.id}</strong><span>Showing transitions connected to <b>${selected.id}</b></span></div><div class="state-graph-legend"><span class="outgoing">Outgoing</span><span class="incoming">Incoming</span><span class="runtime">Active in Play</span></div>`; this.graph.append(header);
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.setAttribute("viewBox", `0 0 900 ${height}`);
    const defs = document.createElementNS("http://www.w3.org/2000/svg", "defs"); for (const [id, color] of [["out-arrow", "#57d3ff"], ["in-arrow", "#64748b"]] as const) { const marker = document.createElementNS("http://www.w3.org/2000/svg", "marker"); marker.setAttribute("id", id); marker.setAttribute("viewBox", "0 0 10 10"); marker.setAttribute("refX", "9"); marker.setAttribute("refY", "5"); marker.setAttribute("markerWidth", "7"); marker.setAttribute("markerHeight", "7"); marker.setAttribute("orient", "auto-start-reverse"); const tip = document.createElementNS("http://www.w3.org/2000/svg", "path"); tip.setAttribute("d", "M 0 0 L 10 5 L 0 10 z"); tip.setAttribute("fill", color); marker.append(tip); defs.append(marker); } svg.append(defs);
    const positions = new Map(form.stateMachine.states.map((state, index) => [state.id, this.#nodePositions.get(graphKey + state.id) ?? { x: 70 + index % 3 * 280, y: 60 + Math.floor(index / 3) * 180 }]));
    const drawEdge = (source: CharacterStateDefinition, transition: StateTransitionDefinition, priority: number, outgoing: boolean): void => { const from = positions.get(source.id)!, to = positions.get(transition.to); if (!to) return; const self = source.id === transition.to, x1 = from.x + 75, y1 = from.y + 42, x2 = to.x + 75, y2 = to.y + 42; const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", self ? `M ${from.x + 130} ${from.y + 18} C ${from.x + 205} ${from.y - 50}, ${from.x + 205} ${from.y + 130}, ${from.x + 130} ${from.y + 68}` : `M ${x1} ${y1} C ${(x1 + x2) / 2} ${y1}, ${(x1 + x2) / 2} ${y2}, ${x2} ${y2}`); path.classList.add("state-edge", outgoing ? "outgoing" : "incoming"); path.setAttribute("marker-end", `url(#${outgoing ? "out-arrow" : "in-arrow"})`); svg.append(path); if (outgoing) { const label = document.createElementNS("http://www.w3.org/2000/svg", "text"); label.classList.add("state-edge-label"); label.setAttribute("x", String(self ? from.x + 175 : (x1 + x2) / 2)); label.setAttribute("y", String(self ? from.y - 4 : (y1 + y2) / 2 - 7)); label.textContent = `${priority + 1}. ${this.#conditionSummary(transition.conditions)}`; svg.append(label); } };
    selected.transitions.forEach((transition, priority) => drawEdge(selected, transition, priority, true)); for (const state of form.stateMachine.states) if (state !== selected) state.transitions.forEach((transition, priority) => { if (transition.to === selected.id) drawEdge(state, transition, priority, false); });
    form.stateMachine.states.forEach((state, index) => { const pos = positions.get(state.id)!, group = document.createElementNS("http://www.w3.org/2000/svg", "g"); group.classList.add("state-node"); if (index === this.#state) group.classList.add("selected"); if (active.form === form.id && active.state === state.id) group.classList.add("active"); group.setAttribute("transform", `translate(${pos.x} ${pos.y})`); const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect"); rect.setAttribute("width", "150"); rect.setAttribute("height", "84"); const title = document.createElementNS("http://www.w3.org/2000/svg", "text"); title.setAttribute("x", "12"); title.setAttribute("y", "28"); title.textContent = state.id; const detail = document.createElementNS("http://www.w3.org/2000/svg", "text"); detail.setAttribute("x", "12"); detail.setAttribute("y", "55"); detail.textContent = `${state.behavior ?? state.id} · ${state.transitions.length} exits`; let moved = false; group.addEventListener("pointerdown", (event) => { group.setPointerCapture(event.pointerId); const start = { x: event.clientX, y: event.clientY, nodeX: pos.x, nodeY: pos.y }; const move = (next: PointerEvent) => { const scale = 900 / Math.max(1, svg.getBoundingClientRect().width), current = { x: Math.max(0, start.nodeX + (next.clientX - start.x) * scale), y: Math.max(0, start.nodeY + (next.clientY - start.y) * scale) }; moved = true; this.#nodePositions.set(graphKey + state.id, current); group.setAttribute("transform", `translate(${current.x} ${current.y})`); }; const end = () => { group.removeEventListener("pointermove", move); group.removeEventListener("pointerup", end); if (moved) this.#renderGraph(); }; group.addEventListener("pointermove", move); group.addEventListener("pointerup", end); }); group.addEventListener("click", () => { if (moved) return; this.#state = index; this.render(); }); group.append(rect, title, detail); svg.append(group); }); this.graph.append(svg);
  }
  #unique(base: string, ids: string[]): string { let index = 1, result = base; while (ids.includes(result)) result = `${base}-${index++}`; return result; }
}
