export interface ParallaxLayerDefinition { id: string; image: string; plane: "back" | "front"; factorX: number; factorY: number; offsetX?: number; offsetY?: number; repeatX?: boolean; repeatY?: boolean; opacity?: number; }
export interface MessageDefinition { id: string; speaker?: string; text: string; durationTicks?: number; }
export interface VisualEffectDefinition { id: string; kind: "fadeIn" | "fadeOut" | "flash"; color: string; durationTicks: number; }
export interface PresentationDefinition { parallaxLayers?: ParallaxLayerDefinition[]; messages?: MessageDefinition[]; effects?: VisualEffectDefinition[]; }
export interface CameraPresentation { mode: "follow" | "fixed"; x: number; y: number; startX: number; startY: number; durationTicks: number; elapsedTicks: number; }
export interface PresentationSnapshot { camera: CameraPresentation; message: MessageDefinition | null; messageTicks: number; effect: VisualEffectDefinition | null; effectTicks: number; }
const ids = <T extends { id: string }>(items: T[], name: string): void => { const seen = new Set<string>(); for (const item of items) { if (!item.id.trim() || seen.has(item.id)) throw new Error(`invalid or duplicate ${name}: ${item.id}`); seen.add(item.id); } };
export function validatePresentation(value: PresentationDefinition): void { const layers = value.parallaxLayers ?? [], messages = value.messages ?? [], effects = value.effects ?? []; ids(layers, "parallax layer"); ids(messages, "message"); ids(effects, "visual effect"); for (const layer of layers) if (!layer.image?.trim() || !["back", "front"].includes(layer.plane) || ![layer.factorX, layer.factorY, layer.opacity ?? 1].every(Number.isFinite) || (layer.opacity ?? 1) < 0 || (layer.opacity ?? 1) > 1) throw new Error(`invalid parallax layer: ${layer.id}`); for (const message of messages) if (!message.text.trim() || !Number.isInteger(message.durationTicks ?? 0) || (message.durationTicks ?? 0) < 0) throw new Error(`invalid message: ${message.id}`); for (const effect of effects) if (!["fadeIn", "fadeOut", "flash"].includes(effect.kind) || !/^#[0-9a-f]{6}$/i.test(effect.color) || !Number.isInteger(effect.durationTicks) || effect.durationTicks < 1) throw new Error(`invalid visual effect: ${effect.id}`); }
export class PresentationState {
  readonly definition: PresentationDefinition; #camera: CameraPresentation = { mode: "follow", x: 0, y: 0, startX: 0, startY: 0, durationTicks: 0, elapsedTicks: 0 }; #message: MessageDefinition | null = null; #messageTicks = 0; #effect: VisualEffectDefinition | null = null; #effectTicks = 0;
  constructor(definition: PresentationDefinition = {}) { validatePresentation(definition); this.definition = structuredClone(definition); }
  reset(): void { this.#camera = { mode: "follow", x: 0, y: 0, startX: 0, startY: 0, durationTicks: 0, elapsedTicks: 0 }; this.#message = null; this.#messageTicks = 0; this.#effect = null; this.#effectTicks = 0; }
  execute(action: { type: string; [key: string]: unknown }, currentX = 0, currentY = 0): void { if (action.type === "setCamera") { const mode = action.mode as "follow" | "fixed"; if (!["follow", "fixed"].includes(mode) || !Number.isInteger(action.durationTicks) || Number(action.durationTicks) < 0 || (mode === "fixed" && (!Number.isFinite(action.x) || !Number.isFinite(action.y)))) throw new Error("invalid camera presentation action"); this.#camera = { mode, x: mode === "fixed" ? Number(action.x) : 0, y: mode === "fixed" ? Number(action.y) : 0, startX: currentX, startY: currentY, durationTicks: Number(action.durationTicks), elapsedTicks: 0 }; } else if (action.type === "showMessage") { const message = this.definition.messages?.find((item) => item.id === action.message); if (!message) throw new Error(`message does not exist: ${String(action.message)}`); this.#message = message; this.#messageTicks = 0; } else if (action.type === "hideMessage") { this.#message = null; this.#messageTicks = 0; } else if (action.type === "playEffect") { const effect = this.definition.effects?.find((item) => item.id === action.effect); if (!effect) throw new Error(`visual effect does not exist: ${String(action.effect)}`); this.#effect = effect; this.#effectTicks = 0; } else throw new Error(`unregistered presentation action: ${action.type}`); }
  step(): void { if (this.#camera.elapsedTicks < this.#camera.durationTicks) this.#camera.elapsedTicks++; if (this.#message) { this.#messageTicks++; if ((this.#message.durationTicks ?? 0) > 0 && this.#messageTicks >= this.#message.durationTicks!) this.#message = null; } if (this.#effect) { this.#effectTicks++; if (this.#effectTicks >= this.#effect.durationTicks) this.#effect = null; } }
  get snapshot(): PresentationSnapshot { return { camera: { ...this.#camera }, message: this.#message && { ...this.#message }, messageTicks: this.#messageTicks, effect: this.#effect && { ...this.#effect }, effectTicks: this.#effectTicks }; }
  cameraPosition(followX: number, followY: number): { x: number; y: number } { const progress = this.#camera.durationTicks ? Math.min(1, this.#camera.elapsedTicks / this.#camera.durationTicks) : 1, eased = progress * progress * (3 - 2 * progress), targetX = this.#camera.mode === "follow" ? followX : this.#camera.x, targetY = this.#camera.mode === "follow" ? followY : this.#camera.y; return { x: this.#camera.startX + (targetX - this.#camera.startX) * eased, y: this.#camera.startY + (targetY - this.#camera.startY) * eased }; }
  effectOpacity(): number { if (!this.#effect) return 0; const progress = this.#effectTicks / this.#effect.durationTicks; if (this.#effect.kind === "fadeIn") return 1 - progress; if (this.#effect.kind === "fadeOut") return progress; return progress < .5 ? progress * 2 : (1 - progress) * 2; }
}
