import assert from "node:assert/strict";
import { test } from "node:test";
import { CombatantState, activeAttackboxes, resolveCombat, validateCombat } from "../test-dist/combat.mjs";

const definition = { damageTypes: [{ id: "physical" }], profiles: [
  { id: "warrior", faction: "heroes", maxHealth: 3, hurtboxes: [{ id: "body", x: 2, y: 1, width: 8, height: 15 }], attacks: [{ id: "sword", states: ["striking"], frames: [1, 2], x: 9, y: 3, width: 9, height: 5, damageType: "physical", damage: 1, hitOnce: true }] , guards: [{ id: "shield", states: ["guarding"], x: 8, y: 1, width: 4, height: 14, facingOnly: true }] },
  { id: "enemy", faction: "monsters", maxHealth: 2, invulnerabilityTicks: 2, hurtboxes: [{ id: "body", x: 0, y: 0, width: 10, height: 16 }] },
] };
const pose = (x, face, state, frame = 0, activation = 1) => ({ x, y: 0, width: 12, face, state, frame, activation });

test("combat profiles are closed, typed and validate references", () => { validateCombat(definition); assert.throws(() => validateCombat({ damageTypes: [{ id: "physical" }], profiles: [{ ...definition.profiles[0], attacks: [{ ...definition.profiles[0].attacks[0], damageType: "magic" }] }] }), /invalid attack/); });
test("frame windows and facing mirror attack boxes", () => { const warrior = definition.profiles[0]; assert.equal(activeAttackboxes(warrior, pose(10, "right", "striking", 0)).length, 0); assert.equal(activeAttackboxes(warrior, pose(10, "right", "striking", 1))[0].x, 19); assert.equal(activeAttackboxes(warrior, pose(10, "left", "striking", 1))[0].x, 4); });
test("hits damage once per activation and respect invulnerability", () => { const attacker = new CombatantState(definition.profiles[0]), defender = new CombatantState(definition.profiles[1]); const hit = resolveCombat(attacker, pose(0, "right", "striking", 1), defender, pose(12, "left", "walking")); assert.equal(hit?.blocked, false); assert.equal(defender.health, 1); assert.equal(resolveCombat(attacker, pose(0, "right", "striking", 2), defender, pose(12, "left", "walking")), null); attacker.step(); defender.step(); attacker.step(); defender.step(); resolveCombat(attacker, pose(0, "right", "striking", 1, 2), defender, pose(12, "left", "walking")); assert.equal(defender.alive, false); });
test("a facing guard blocks an overlapping attack", () => { const attacker = new CombatantState(definition.profiles[0]), defender = new CombatantState({ ...definition.profiles[0], faction: "guards" }); const hit = resolveCombat(attacker, pose(0, "right", "striking", 1), defender, pose(12, "left", "guarding")); assert.equal(hit?.blocked, true); assert.equal(defender.health, 3); });
test("historical scaled contact reaches the inset player body", () => { const playerProfile = { id: "player", faction: "player", maxHealth: 1, hurtboxes: [{ id: "body", x: 25, y: 25, width: 14, height: 95 }] }, enemyProfile = { id: "enemy", faction: "enemies", maxHealth: 1, hurtboxes: [{ id: "body", x: 0, y: 0, width: 64, height: 71 }], attacks: [{ id: "contact", states: ["CHAR_STATE_RUNNING"], x: 0, y: 0, width: 64, height: 71, damageType: "physical", damage: 1 }] }; const player = new CombatantState(playerProfile), enemy = new CombatantState(enemyProfile); const hit = resolveCombat(enemy, { x: 25, y: 100, width: 64, face: "right", state: "CHAR_STATE_RUNNING", frame: 0, activation: 1 }, player, { x: 0, y: 0, width: 64, face: "right", state: "walking", frame: 0, activation: 1 }); assert.equal(hit?.damage, 1); assert.equal(player.alive, false); });
test("the composed sword only hits across the visible blade", () => { const swordProfile = { id: "player", faction: "player", maxHealth: 1, hurtboxes: [{ id: "body", x: 25, y: 25, width: 14, height: 95 }], attacks: [{ id: "melee", states: ["golpear"], frames: [0], x: 64, y: 24, width: 64, height: 28, damageType: "physical", damage: 1 }] }, enemyProfile = { id: "enemy", faction: "enemies", maxHealth: 1, hurtboxes: [{ id: "body", x: 0, y: 0, width: 64, height: 20 }] }, sword = new CombatantState(swordProfile), enemy = new CombatantState(enemyProfile), pose = { x: 0, y: 0, width: 64, face: "right", state: "golpear", frame: 0, activation: 1 }; assert.equal(resolveCombat(sword, pose, enemy, { x: 80, y: 60, width: 64, face: "left", state: "running", frame: 0, activation: 1 }), null); assert.ok(resolveCombat(sword, { ...pose, activation: 2 }, enemy, { x: 80, y: 30, width: 64, face: "left", state: "running", frame: 0, activation: 1 })); assert.equal(enemy.alive, false); });
test("continuous contact can kill the same respawned target again", () => { const attacker = new CombatantState({ id: "hazard", faction: "enemies", maxHealth: 1, hurtboxes: [{ id: "body", x: 0, y: 0, width: 10, height: 10 }], attacks: [{ id: "contact", states: ["idle"], x: 0, y: 0, width: 10, height: 10, damageType: "physical", damage: 1, hitOnce: false }] }), target = new CombatantState({ id: "hero", faction: "player", maxHealth: 1, hurtboxes: [{ id: "body", x: 0, y: 0, width: 10, height: 10 }] }); const hazardPose = pose(0, "right", "idle"), targetPose = pose(0, "right", "walk"); assert.ok(resolveCombat(attacker, hazardPose, target, targetPose)); assert.equal(target.alive, false); target.reset(); assert.ok(resolveCombat(attacker, hazardPose, target, targetPose)); assert.equal(target.alive, false); });
test("an all-facing guard blocks sword hits while contact stays active", () => { const sword = new CombatantState({ ...definition.profiles[0], attacks: [{ id: "sword", states: ["striking"], x: 0, y: 0, width: 10, height: 10, damageType: "physical", damage: 1 }] }), plant = new CombatantState({ id: "plant", faction: "enemies", maxHealth: 1, hurtboxes: [{ id: "body", x: 0, y: 0, width: 10, height: 10 }], guards: [{ id: "immune", states: ["idle"], x: 0, y: 0, width: 10, height: 10, damageTypes: ["physical"], facingOnly: false }], attacks: [{ id: "contact", states: ["idle"], x: 0, y: 0, width: 10, height: 10, damageType: "physical", damage: 1, hitOnce: false }] }); assert.equal(resolveCombat(sword, pose(0, "right", "striking"), plant, pose(0, "right", "idle"))?.blocked, true); assert.equal(plant.alive, true); assert.ok(resolveCombat(plant, pose(0, "right", "idle"), sword, pose(0, "right", "walking"))); });
