import assert from "node:assert/strict";
import { test } from "node:test";
import { PreviewRuntime } from "../test-dist/preview-runtime.mjs";

const width = 20, height = 10, collisions = Array(width * height).fill(0); for (let x = 0; x < width; ++x) collisions[8 * width + x] = 2;
const level = { map: { width, height, tileWidth: 8, tileHeight: 8, tileset: { tileCount: 1, columns: 1, image: "x" }, layers: { tiles: Array(width * height).fill(0), frontTiles: Array(width * height).fill(0), collisions } }, entities: { checkpoints: [{ pl_x: 16, pl_y: 43, pl_face: "right" }], platforms: [{ id: 1, attributes: { ini_x: 0, ini_y: 0, width: 8, height: 8, recursive: 1 }, actions: { action: [{ direction: "right", desp: 3, speed: 1, wait: 2 }, { direction: "left", desp: 3, speed: 1, wait: 0 }] } }], hazards: [] } };
test("preview advances deterministically in fixed ticks and reset is exact", () => { const runtime = new PreviewRuntime(level); for (let i = 0; i < 3; ++i) runtime.step(); assert.equal(runtime.bodies[0].x, 3); for (let i = 0; i < 3; ++i) runtime.step(); assert.equal(runtime.bodies[0].x, 2); runtime.reset(); assert.equal(runtime.tick, 0); assert.equal(runtime.bodies[0].x, 0); });
test("two runtimes produce identical snapshots", () => { const a = new PreviewRuntime(level); const b = new PreviewRuntime(level); for (let i = 0; i < 100; ++i) { a.step(); b.step(); } assert.deepEqual(a.bodies, b.bodies); });
test("visible hazards kill the player", () => { const data = structuredClone(level); data.entities.hazards = [{ id: 9, attributes: { ini_x: 21, ini_y: 43, width: 13, height: 21, trigger: 1 }, actions: { action: { direction: "stop", desp: 0, speed: 0, wait: 0 } } }]; const runtime = new PreviewRuntime(data); runtime.step(); assert.equal(runtime.player.state, "dead"); });
test("invulnerable debug mode reports danger without killing the player", () => { const data = structuredClone(level); data.entities.hazards = [{ id: 9, attributes: { ini_x: 21, ini_y: 43, width: 13, height: 21, trigger: 1 }, actions: { action: { direction: "stop", desp: 0, speed: 0, wait: 0 } } }]; const runtime = new PreviewRuntime(data); runtime.setInvulnerable(true); runtime.step(); assert.equal(runtime.player.state, "stop"); assert.equal(runtime.dangerContact, true); });
test("deactivated hazards are neither rendered nor lethal", () => { const data = structuredClone(level); data.entities.hazards = [{ id: 9, attributes: { ini_x: 21, ini_y: 43, width: 13, height: 21, trigger: 1 }, actions: { action: { direction: "deactivate", desp: 0, speed: 0, wait: 20 } } }]; const runtime = new PreviewRuntime(data); runtime.step(); assert.equal(runtime.player.state, "stop"); assert.equal(runtime.bodies.some((body) => body.key === "hazards:9"), false); });
test("only lasers enabled by default are initially lethal", () => { const data = structuredClone(level); data.entities.lasers = [{ id: 1, x: 16, y: 40, bb_x: 5, bb_y: 3, bb_width: 13, bb_height: 21, default_trigger: 1 }, { id: 2, x: 16, y: 40, bb_x: 5, bb_y: 3, bb_width: 13, bb_height: 21, default_trigger: 0 }]; const runtime = new PreviewRuntime(data); runtime.step(); assert.equal(runtime.player.state, "dead"); assert.equal(runtime.bodies.some((body) => body.key === "lasers:1"), true); assert.equal(runtime.bodies.some((body) => body.key === "lasers:2"), false); });
