import assert from "node:assert/strict"; import { test } from "node:test"; import { WebPlayer } from "../test-dist/web-player.mjs";
function level() { const width = 20, height = 10, tileCount = 1, cells = Array(width * height).fill(0); for (let x = 0; x < width; ++x) cells[8 * width + x] = tileCount + 1; return { map: { width, height, tileWidth: 8, tileHeight: 8, tileset: { tileCount, columns: 1, image: "x" }, layers: { tiles: Array(width * height).fill(0), frontTiles: Array(width * height).fill(0), collisions: cells } }, entities: { checkpoints: [{ pl_x: 16, pl_y: 43, pl_face: "right" }] } }; }
const none = { left: false, right: false, up: false, down: false, action: false };
test("player spawns from checkpoint, runs and collides with world", () => { const player = new WebPlayer(level()); assert.equal(player.snapshot.x, 16); for (let i = 0; i < 100; ++i) player.step({ ...none, right: true }); assert.ok(player.snapshot.x <= 142); assert.equal(player.snapshot.face, "right"); });
test("jump arc and reset are deterministic", () => { const a = new WebPlayer(level()), b = new WebPlayer(level()); for (let i = 0; i < 60; ++i) { const input = { ...none, up: i === 0, right: true }; a.step(input); b.step(input); } assert.deepEqual(a.snapshot, b.snapshot); a.reset(); assert.deepEqual(a.snapshot, { x: 16, y: 43, state: "stop", face: "right", verticalSpeed: 3 }); });
test("stairs use their collision GID and allow controlled climbing", () => { const data = level(); data.map.layers.collisions[6 * data.map.width + 3] = 4; data.map.layers.collisions[7 * data.map.width + 3] = 4; const player = new WebPlayer(data); player.step({ ...none, up: true }); assert.equal(player.snapshot.state, "climbing"); assert.equal(player.snapshot.y, 41); });
test("player remains attached to stairs while vertical input is released", () => { const data = level(); for (let y = 3; y < 8; ++y) data.map.layers.collisions[y * data.map.width + 3] = 4; const player = new WebPlayer(data); player.step({ ...none, up: true }); const y = player.snapshot.y; for (let i = 0; i < 10; ++i) player.step(none); assert.equal(player.snapshot.state, "climbing"); assert.equal(player.snapshot.y, y); });
test("stairs can be entered downwards from their top tile", () => { const data = level(); data.entities.checkpoints[0].pl_y = 35; data.map.layers.collisions[7 * data.map.width + 3] = 5; data.map.layers.collisions[8 * data.map.width + 3] = 4; const player = new WebPlayer(data); player.step({ ...none, down: true }); assert.equal(player.snapshot.state, "climbing"); assert.equal(player.snapshot.y, 37); });
test("jump is rearmed after every landing", () => { const player = new WebPlayer(level()); player.step({ ...none, up: true }); const firstTop = player.snapshot.y; for (let i = 0; i < 80; ++i) { player.step(none); if (player.snapshot.y < firstTop) break; } for (let i = 0; i < 80 && player.snapshot.state !== "stop"; ++i) player.step(none); const floorY = player.snapshot.y; player.step({ ...none, up: true }); assert.equal(player.snapshot.state, "jumping"); assert.ok(player.snapshot.y < floorY); });
test("moving platforms carry a player standing on them", () => { const data = level(); data.entities.checkpoints[0].pl_y = 19; const player = new WebPlayer(data); player.step(none, [{ key: "p", x: 16, y: 41, width: 32, height: 8, dx: 2, dy: 1 }]); assert.equal(player.snapshot.x, 18); assert.equal(player.snapshot.y, 20); });
test("checkpoint activation changes the deterministic respawn", () => { const data = level(); data.entities.checkpoints.push({ id: 7, chk_x: 16, chk_y: 43, chk_width: 24, chk_height: 24, pl_x: 40, pl_y: 43, pl_face: "left" }); const player = new WebPlayer(data); player.step(none); assert.equal(player.activeCheckpoint, 7); player.reset(); assert.equal(player.snapshot.x, 40); assert.equal(player.snapshot.face, "left"); });
test("falling outside the map enters death and respawns", () => { const data = level(); data.entities.checkpoints[0].pl_y = 103; const player = new WebPlayer(data); player.step(none); assert.equal(player.snapshot.state, "dead"); for (let i = 0; i < 20; ++i) player.step(none); assert.equal(player.snapshot.state, "stop"); assert.equal(player.snapshot.y, 103); });
