import assert from "node:assert/strict"; import { test } from "node:test"; import { WebPlayer } from "../test-dist/web-player.mjs";
function level() { const width = 20, height = 10, tileCount = 1, cells = Array(width * height).fill(0); for (let x = 0; x < width; ++x) cells[8 * width + x] = tileCount + 1; return { map: { width, height, tileWidth: 8, tileHeight: 8, tileset: { tileCount, columns: 1, image: "x" }, layers: { tiles: Array(width * height).fill(0), frontTiles: Array(width * height).fill(0), collisions: cells } }, entities: { checkpoints: [{ pl_x: 16, pl_y: 43, pl_face: "right" }] } }; }
const none = { left: false, right: false, up: false, down: false, action: false };
test("player spawns from checkpoint, runs and collides with world", () => { const player = new WebPlayer(level()); assert.equal(player.snapshot.x, 16); for (let i = 0; i < 100; ++i) player.step({ ...none, right: true }); assert.ok(player.snapshot.x <= 142); assert.equal(player.snapshot.face, "right"); });
test("jump arc and reset are deterministic", () => { const a = new WebPlayer(level()), b = new WebPlayer(level()); for (let i = 0; i < 60; ++i) { const input = { ...none, up: i === 0, right: true }; a.step(input); b.step(input); } assert.deepEqual(a.snapshot, b.snapshot); a.reset(); assert.deepEqual(a.snapshot, { x: 16, y: 43, state: "stop", face: "right", verticalSpeed: 3, collisionX: 21, collisionY: 43, collisionWidth: 13, collisionHeight: 21 }); });
test("Rick is provided through the default declarative form profile", () => { const player = new WebPlayer(level()); assert.equal(player.activeForm, "rick"); assert.equal(player.snapshot.collisionWidth, 13); player.step({ ...none, right: true }); assert.equal(player.snapshot.state, "running"); assert.equal(player.declaredStateTicks, 0); player.step({ ...none, right: true }); assert.equal(player.declaredStateTicks, 1); player.reset(); assert.equal(player.snapshot.state, "stop"); assert.equal(player.declaredStateTicks, 0); });
test("the declarative graph owns idle and running transitions", () => { const player = new WebPlayer(level()); player.step({ ...none, left: true }); assert.equal(player.snapshot.state, "running"); player.step(none); assert.equal(player.snapshot.state, "stop"); player.step({ ...none, action: true, up: true }); assert.equal(player.snapshot.state, "shooting"); player.step({ ...none, right: true }); assert.equal(player.snapshot.state, "running"); });
test("a declarative form transition changes the live controller while preserving the feet", () => {
  const forms = { initialForm: "warrior", forms: [
    { id: "warrior", controller: { standingHeight: 40, collisionWidth: 15, runSpeed: 2 }, stateMachine: { initialState: "stop", states: [{ id: "stop", transitions: [{ to: "stop", conditions: [{ type: "control", control: "action", pressed: true }], actions: [{ type: "setForm", form: "frog" }] }] }] } },
    { id: "frog", controller: { standingHeight: 31, collisionWidth: 29, runSpeed: 4 }, capabilities: { climb: false }, stateMachine: { initialState: "stop", states: [{ id: "stop", transitions: [{ to: "running", conditions: [{ type: "control", control: "right", pressed: true }] }] }, { id: "running", transitions: [] }] } },
  ] };
  const player = new WebPlayer(level(), {}, {}, {}, forms); const feet = player.snapshot.y + player.snapshot.collisionHeight; player.step({ ...none, action: true }); assert.equal(player.activeForm, "frog"); assert.equal(player.snapshot.collisionWidth, 29); assert.equal(player.snapshot.y + player.snapshot.collisionHeight, feet); const x = player.snapshot.x; player.step({ ...none, right: true }); assert.equal(player.snapshot.x, x + 4);
});
test("crouching lowers Rick and reduces his collision height", () => { const player = new WebPlayer(level()); player.step({ ...none, down: true }); assert.equal(player.snapshot.state, "crouching"); assert.equal(player.snapshot.y, 49); assert.equal(player.snapshot.collisionHeight, 15); player.step(none); assert.equal(player.snapshot.state, "stop"); assert.equal(player.snapshot.y, 43); assert.equal(player.snapshot.collisionHeight, 21); });
test("Rick remains crouched when there is no room to stand", () => { const data = level(); for (let x = 2; x <= 4; ++x) data.map.layers.collisions[5 * data.map.width + x] = 2; const player = new WebPlayer(data); player.step({ ...none, down: true }); player.step(none); assert.equal(player.snapshot.state, "crouching"); assert.equal(player.snapshot.collisionHeight, 15); });
test("crouching does not suspend Rick after walking off a ledge", () => { const data = level(); for (let x = 5; x < data.map.width; ++x) data.map.layers.collisions[8 * data.map.width + x] = 0; const player = new WebPlayer(data); const input = { ...none, down: true, right: true }; for (let i = 0; i < 12; ++i) player.step(input); assert.equal(player.snapshot.state, "jumping"); assert.equal(player.snapshot.collisionHeight, 21); });
test("touching only the edge of a staircase still allows crouching", () => { const data = level(); data.map.layers.collisions[8 * data.map.width + 4] = 5; const player = new WebPlayer(data); player.step({ ...none, down: true }); assert.equal(player.snapshot.state, "crouching"); assert.equal(player.snapshot.collisionHeight, 15); });
test("stairs use their collision GID and allow controlled climbing", () => { const data = level(); data.map.layers.collisions[6 * data.map.width + 3] = 4; data.map.layers.collisions[7 * data.map.width + 3] = 4; const player = new WebPlayer(data); player.step({ ...none, up: true }); assert.equal(player.snapshot.state, "climbing"); assert.equal(player.snapshot.y, 41); });
test("player remains attached to stairs while vertical input is released", () => { const data = level(); for (let y = 3; y < 8; ++y) data.map.layers.collisions[y * data.map.width + 3] = 4; const player = new WebPlayer(data); player.step({ ...none, up: true }); const y = player.snapshot.y; for (let i = 0; i < 10; ++i) player.step(none); assert.equal(player.snapshot.state, "climbing"); assert.equal(player.snapshot.y, y); });
test("stairs can be entered downwards from their top tile", () => { const data = level(); data.entities.checkpoints[0].pl_y = 35; data.map.layers.collisions[7 * data.map.width + 3] = 5; data.map.layers.collisions[8 * data.map.width + 3] = 4; const player = new WebPlayer(data); player.step({ ...none, down: true }); assert.equal(player.snapshot.state, "climbing"); assert.equal(player.snapshot.y, 37); });
test("jump is rearmed after every landing", () => { const player = new WebPlayer(level()); player.step({ ...none, up: true }); const firstTop = player.snapshot.y; for (let i = 0; i < 80; ++i) { player.step(none); if (player.snapshot.y < firstTop) break; } for (let i = 0; i < 80 && player.snapshot.state !== "stop"; ++i) player.step(none); const floorY = player.snapshot.y; player.step({ ...none, up: true }); assert.equal(player.snapshot.state, "jumping"); assert.ok(player.snapshot.y < floorY); });
test("moving platforms carry a player standing on them", () => { const data = level(); data.entities.checkpoints[0].pl_y = 19; const player = new WebPlayer(data); player.step(none, [{ key: "p", x: 16, y: 41, width: 32, height: 8, dx: 2, dy: 1 }]); assert.equal(player.snapshot.x, 18); assert.equal(player.snapshot.y, 20); });
test("an ascending platform cannot push Rick inside a solid ceiling", () => { const data = level(); data.entities.checkpoints[0].pl_y = 27; for (const column of [2, 3, 4]) data.map.layers.collisions[2 * data.map.width + column] = 2; const player = new WebPlayer(data); player.step(none, [{ key: "p", x: 16, y: 44, width: 32, height: 8, dx: 0, dy: -4 }]); assert.equal(player.snapshot.y, 24); });
test("checkpoint activation changes the deterministic respawn", () => { const data = level(); data.entities.checkpoints[0].nxt_chks = [7]; data.entities.checkpoints.push({ id: 7, chk_x: 16, chk_y: 43, chk_width: 24, chk_height: 24, pl_x: 40, pl_y: 43, pl_face: "left" }); const player = new WebPlayer(data); player.step(none); assert.equal(player.activeCheckpoint, 7); player.reset(); assert.equal(player.snapshot.x, 40); assert.equal(player.snapshot.face, "left"); });
test("checkpoint activation follows the declared progression graph", () => { const data = level(); data.entities.checkpoints[0].id = 0; data.entities.checkpoints[0].nxt_chks = [1]; data.entities.checkpoints.push({ id: 2, chk_x: 16, chk_y: 43, chk_width: 24, chk_height: 24, pl_x: 80, pl_y: 43, pl_face: "left" }); const player = new WebPlayer(data); player.step(none); assert.equal(player.activeCheckpoint, 0); assert.equal(player.snapshot.x, 16); });
test("death follows the native rising arc before respawning", () => { const data = level(); data.entities.checkpoints[0].pl_y = 103; const player = new WebPlayer(data); player.step(none); assert.equal(player.snapshot.state, "dead"); const start = player.snapshot; player.step(none); assert.equal(player.snapshot.x, start.x + 2); assert.ok(player.snapshot.y < start.y); for (let i = 1; i < 70; ++i) player.step(none); assert.equal(player.snapshot.state, "stop"); assert.equal(player.snapshot.y, 103); });
test("a camera death boundary waits for the descending arc instead of a fixed timer", () => { const player = new WebPlayer(level()); player.kill(); for (let i = 0; i < 70; ++i) player.step(none, [], [], 300); assert.equal(player.snapshot.state, "dead"); for (let i = 0; i < 100 && player.snapshot.state === "dead"; ++i) player.step(none, [], [], 300); assert.equal(player.snapshot.state, "stop"); assert.equal(player.snapshot.y, 43); });
test("debug placement moves the player by its feet without changing respawn", () => { const player = new WebPlayer(level()); player.placeAtFeet(80, 40); assert.equal(player.snapshot.x, 69); assert.equal(player.snapshot.y, 19); assert.equal(player.snapshot.state, "stop"); player.reset(); assert.equal(player.snapshot.x, 16); assert.equal(player.snapshot.y, 43); });
test("action combinations expose shooting, bombing and hitting states", () => { const player = new WebPlayer(level()); player.step({ ...none, action: true, up: true }); assert.equal(player.snapshot.state, "shooting"); player.step(none); player.step({ ...none, action: true, down: true }); assert.equal(player.snapshot.state, "bombing"); player.step(none); player.step({ ...none, action: true, left: true }); assert.equal(player.snapshot.state, "hitting"); assert.equal(player.snapshot.face, "left"); });
test("action states hold Rick still and a held hit expires after 400 ms", () => { const player = new WebPlayer(level()), hit = { ...none, action: true, right: true }; const x = player.snapshot.x; player.step(hit); assert.equal(player.snapshot.state, "hitting"); assert.equal(player.snapshot.x, x); for (let i = 0; i < 20; ++i) player.step(hit); assert.equal(player.snapshot.state, "hitting"); player.step(hit); assert.equal(player.snapshot.state, "stop"); assert.equal(player.snapshot.x, x); player.step(hit); assert.equal(player.snapshot.state, "hitting"); });
test("player geometry and movement can use a non-Rick controller profile", () => { const player = new WebPlayer(level(), { spriteWidth: 9, collisionWidth: 7, collisionOffsetX: 1, crouchingHeight: 11, runSpeed: 4 }); assert.equal(player.snapshot.collisionX, 17); assert.equal(player.snapshot.collisionWidth, 7); player.step({ ...none, right: true }); assert.equal(player.snapshot.x, 20); player.step({ ...none, down: true }); assert.equal(player.snapshot.state, "crouching"); assert.equal(player.snapshot.collisionHeight, 11); });
test("jump, crouch and climb can be removed from a player profile", () => { const data = level(); data.map.layers.collisions[6 * data.map.width + 3] = 4; data.map.layers.collisions[7 * data.map.width + 3] = 4; const player = new WebPlayer(data, {}, { jump: false, crouch: false, climb: false }); player.step({ ...none, up: true }); assert.equal(player.snapshot.state, "stop"); player.step({ ...none, down: true }); assert.equal(player.snapshot.state, "stop"); assert.equal(player.snapshot.collisionHeight, 21); });
test("ground actions use configurable chords and optional abilities", () => { const remapped = new WebPlayer(level(), {}, {}, { up: "hitting" }); remapped.step({ ...none, action: true, up: true }); assert.equal(remapped.snapshot.state, "hitting"); const passive = new WebPlayer(level(), {}, { shoot: false, bomb: false, hit: false }); passive.step({ ...none, action: true, right: true }); assert.equal(passive.snapshot.state, "running"); });
