#include "combat.h"
#include "data_loading.h"
#include <algorithm>
#include <cmath>
#include <sstream>

namespace {
bool Active(const CombatBox& box, const CombatPose& pose) { return (box.states.empty() || std::find(box.states.begin(), box.states.end(), pose.state) != box.states.end()) && (box.frames.empty() || std::find(box.frames.begin(), box.frames.end(), pose.frame) != box.frames.end()); }
WorldCombatBox WorldBox(const CombatBox& box, const CombatPose& pose) { WorldCombatBox result = { box.id, pose.x + (pose.facing_left ? pose.width - box.x - box.width : box.x), pose.y + box.y, box.width, box.height }; return result; }
bool Overlap(const WorldCombatBox& a, const WorldCombatBox& b) { return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y; }
std::vector<std::string> Strings(const nlohmann::json& value, const char* key) { std::vector<std::string> out; if (value.contains(key)) for (nlohmann::json::const_iterator it = value.at(key).begin(); it != value.at(key).end(); ++it) out.push_back(it->get<std::string>()); return out; }
std::vector<int> Frames(const nlohmann::json& value) { std::vector<int> out; if (value.contains("frames")) for (nlohmann::json::const_iterator it = value.at("frames").begin(); it != value.at("frames").end(); ++it) out.push_back(it->get<int>()); return out; }
CombatBox Box(const nlohmann::json& value) { CombatBox box = { value.at("id").get<std::string>(), value.at("x").get<double>(), value.at("y").get<double>(), value.at("width").get<double>(), value.at("height").get<double>(), Strings(value, "states"), Frames(value), value.value("damageType", ""), value.value("damage", 0), value.value("hitOnce", true), value.value("facingOnly", true), value.value("knockbackX", 0.0), value.value("knockbackY", 0.0), Strings(value, "damageTypes") }; if (box.id.empty() || box.width <= 0 || box.height <= 0) throw DataLoadError("Invalid combat box: " + box.id); return box; }
std::vector<CombatBox> Boxes(const nlohmann::json& value, const char* key) { std::vector<CombatBox> out; if (value.contains(key)) for (nlohmann::json::const_iterator it = value.at(key).begin(); it != value.at(key).end(); ++it) out.push_back(Box(*it)); return out; }
std::vector<WorldCombatBox> ActiveBoxes(const std::vector<CombatBox>& boxes, const CombatPose& pose) { std::vector<WorldCombatBox> out; for (std::vector<CombatBox>::const_iterator it = boxes.begin(); it != boxes.end(); ++it) if (Active(*it, pose)) out.push_back(WorldBox(*it, pose)); return out; }
}

CombatCatalog::CombatCatalog(const nlohmann::json& definition) { if (definition.empty()) return; std::set<std::string> damage_types; for (nlohmann::json::const_iterator it = definition.at("damageTypes").begin(); it != definition.at("damageTypes").end(); ++it) if (!damage_types.insert(it->at("id").get<std::string>()).second) throw DataLoadError("Duplicate damage type"); for (nlohmann::json::const_iterator it = definition.at("profiles").begin(); it != definition.at("profiles").end(); ++it) { CombatProfile profile = { it->at("id").get<std::string>(), it->at("faction").get<std::string>(), it->at("maxHealth").get<int>(), it->value("invulnerabilityTicks", 0), Boxes(*it, "hurtboxes"), Boxes(*it, "attacks"), Boxes(*it, "guards") }; if (profile.id.empty() || profile.faction.empty() || profile.max_health < 1 || profile.hurtboxes.empty() || profiles_.count(profile.id)) throw DataLoadError("Invalid combat profile: " + profile.id); for (std::vector<CombatBox>::const_iterator attack = profile.attacks.begin(); attack != profile.attacks.end(); ++attack) if (!damage_types.count(attack->damage_type) || attack->damage < 1 || attack->states.empty()) throw DataLoadError("Invalid combat attack: " + attack->id); profiles_[profile.id] = profile; } }
const CombatProfile* CombatCatalog::Find(const std::string& id) const { std::map<std::string, CombatProfile>::const_iterator it = profiles_.find(id); return it == profiles_.end() ? NULL : &it->second; }
CombatantState::CombatantState(const CombatProfile* profile) : profile_(profile), health_(profile ? profile->max_health : 0), invulnerability_(0) {}
void CombatantState::Reset() { health_ = profile_ ? profile_->max_health : 0; invulnerability_ = 0; hits_.clear(); } void CombatantState::Step() { if (invulnerability_ > 0) --invulnerability_; } bool CombatantState::Alive() const { return health_ > 0; } int CombatantState::Health() const { return health_; } const CombatProfile* CombatantState::Profile() const { return profile_; }
bool CombatantState::CanHit(const std::string& attack, int activation) const { std::ostringstream key; key << attack << ':' << activation; return !hits_.count(key.str()); } void CombatantState::RecordHit(const std::string& attack, int activation) { std::ostringstream key; key << attack << ':' << activation; hits_.insert(key.str()); }
bool CombatantState::Receive(const CombatHit& hit) { if (hit.blocked || invulnerability_ > 0 || !Alive()) return false; health_ = std::max(0, health_ - hit.damage); invulnerability_ = profile_->invulnerability_ticks; return true; }
std::vector<WorldCombatBox> ActiveHurtboxes(const CombatProfile& profile, const CombatPose& pose) { return ActiveBoxes(profile.hurtboxes, pose); } std::vector<WorldCombatBox> ActiveAttackboxes(const CombatProfile& profile, const CombatPose& pose) { return ActiveBoxes(profile.attacks, pose); } std::vector<WorldCombatBox> ActiveGuardboxes(const CombatProfile& profile, const CombatPose& pose) { return ActiveBoxes(profile.guards, pose); }
bool ResolveCombat(CombatantState& attacker, const CombatPose& attacker_pose, CombatantState& defender, const CombatPose& defender_pose, CombatHit* result, bool friendly_fire) { if (!attacker.Profile() || !defender.Profile() || !attacker.Alive() || !defender.Alive() || (!friendly_fire && attacker.Profile()->faction == defender.Profile()->faction)) return false; const std::vector<WorldCombatBox> hurts = ActiveHurtboxes(*defender.Profile(), defender_pose); for (std::vector<CombatBox>::const_iterator attack = attacker.Profile()->attacks.begin(); attack != attacker.Profile()->attacks.end(); ++attack) { if (!Active(*attack, attacker_pose) || (attack->hit_once && !attacker.CanHit(attack->id, attacker_pose.activation))) continue; const WorldCombatBox attack_box = WorldBox(*attack, attacker_pose); bool overlaps = false; for (std::vector<WorldCombatBox>::const_iterator hurt = hurts.begin(); hurt != hurts.end(); ++hurt) if (Overlap(attack_box, *hurt)) overlaps = true; if (!overlaps) continue; bool blocked = false; for (std::vector<CombatBox>::const_iterator guard = defender.Profile()->guards.begin(); guard != defender.Profile()->guards.end(); ++guard) if (Active(*guard, defender_pose) && (guard->damage_types.empty() || std::find(guard->damage_types.begin(), guard->damage_types.end(), attack->damage_type) != guard->damage_types.end()) && (!guard->facing_only || defender_pose.facing_left != attacker_pose.facing_left) && Overlap(attack_box, WorldBox(*guard, defender_pose))) { blocked = true; break; } CombatHit hit = { attack->id, attack->damage_type, blocked, false, attack->damage, attack->knockback_x * (attacker_pose.facing_left ? -1 : 1), attack->knockback_y }; if (attack->hit_once) attacker.RecordHit(attack->id, attacker_pose.activation); hit.applied = defender.Receive(hit); if (result) *result = hit; return true; } return false; }
