#include "gameplay_program.h"
#include "data_loading.h"
#include <cmath>

namespace {
bool BuiltInEvent(const std::string& id) { return id == "killed" || id == "landed"; }
std::string JsonType(const nlohmann::json& value) { if (value.is_boolean()) return "boolean"; if (value.is_number()) return "number"; if (value.is_string()) return "string"; return "invalid"; }
bool Compare(double left, const std::string& op, double right) { if (op == "greater") return left > right; if (op == "greaterOrEqual") return left >= right; if (op == "lower") return left < right; if (op == "lowerOrEqual") return left <= right; throw DataLoadError("Invalid gameplay comparison: " + op); }
}

GameplayProgram::RunningStep::RunningStep(const nlohmann::json& value) : definition(value), remaining(value.value("ticks", 0)), index(0), complete(false) { if (value.value("type", "") == "parallel") for (nlohmann::json::const_iterator it = value.at("steps").begin(); it != value.at("steps").end(); ++it) children.push_back(std::shared_ptr<RunningStep>(new RunningStep(*it))); }

GameplayProgram::GameplayProgram(const nlohmann::json& definition) : definition_(definition.is_null() ? nlohmann::json::object() : definition) {
  const nlohmann::json flags = definition_.value("flags", nlohmann::json::array());
  for (nlohmann::json::const_iterator it = flags.begin(); it != flags.end(); ++it) { const std::string id = it->at("id").get<std::string>(), type = it->at("type").get<std::string>(); if (id.empty() || initial_flags_.count(id)) throw DataLoadError("Invalid or duplicate gameplay flag: " + id); if (JsonType(it->at("initial")) != type || (it->at("initial").is_number() && !std::isfinite(it->at("initial").get<double>()))) throw DataLoadError("Invalid initial value for gameplay flag: " + id); initial_flags_[id] = it->at("initial"); }
  const nlohmann::json events = definition_.value("events", nlohmann::json::array()); for (nlohmann::json::const_iterator it = events.begin(); it != events.end(); ++it) { const std::string id = it->at("id").get<std::string>(); if (id.empty() || BuiltInEvent(id) || !declared_events_.insert(id).second) throw DataLoadError("Invalid, duplicate or reserved gameplay event: " + id); }
  const nlohmann::json sequences = definition_.value("sequences", nlohmann::json::array()); for (nlohmann::json::const_iterator it = sequences.begin(); it != sequences.end(); ++it) { const std::string id = it->at("id").get<std::string>(); if (id.empty() || sequences_.count(id) || it->at("steps").empty()) throw DataLoadError("Invalid or duplicate gameplay sequence: " + id); sequences_[id] = *it; }
  flags_ = initial_flags_;
  for (std::map<std::string, nlohmann::json>::const_iterator sequence = sequences_.begin(); sequence != sequences_.end(); ++sequence) for (nlohmann::json::const_iterator step = sequence->second.at("steps").begin(); step != sequence->second.at("steps").end(); ++step) ValidateStep(*step); Reset();
}
void GameplayProgram::Reset() { flags_ = initial_flags_; events_.clear(); running_.clear(); }
void GameplayProgram::BeginTick() { events_.clear(); }
const nlohmann::json& GameplayProgram::Flag(const std::string& id) const { std::map<std::string, nlohmann::json>::const_iterator it = flags_.find(id); if (it == flags_.end()) throw DataLoadError("Gameplay flag does not exist: " + id); return it->second; }
bool GameplayProgram::HasEvent(const std::string& id) const { return events_.count(id) != 0; }
void GameplayProgram::SetEventSink(const std::function<void(const std::string&)>& sink) { event_sink_ = sink; }
void GameplayProgram::ValidateAction(const nlohmann::json& action) const { const std::string type = action.at("type").get<std::string>(); if (type == "emitEvent") { const std::string id = action.at("event").get<std::string>(); if (!BuiltInEvent(id) && !declared_events_.count(id)) throw DataLoadError("Gameplay event does not exist: " + id); return; } if (type != "setFlag" && type != "toggleFlag" && type != "incrementFlag") throw DataLoadError("Unknown gameplay action: " + type); const std::string id = action.at("flag").get<std::string>(); const nlohmann::json& flag = Flag(id); if (type == "toggleFlag" && !flag.is_boolean()) throw DataLoadError("Gameplay flag must be boolean: " + id); if (type == "incrementFlag" && (!flag.is_number() || !action.at("amount").is_number() || !std::isfinite(action.at("amount").get<double>()))) throw DataLoadError("Gameplay flag must be numeric: " + id); if (type == "setFlag" && JsonType(flag) != JsonType(action.at("value"))) throw DataLoadError("Gameplay flag value has wrong type: " + id); }
void GameplayProgram::ValidateTrigger(const nlohmann::json& definition) const { if (definition.contains("conditions")) for (nlohmann::json::const_iterator it = definition.at("conditions").begin(); it != definition.at("conditions").end(); ++it) { const std::string type = it->at("type").get<std::string>(); if (type == "event") { const std::string id = it->at("event").get<std::string>(); if (!BuiltInEvent(id) && !declared_events_.count(id)) throw DataLoadError("Gameplay event does not exist: " + id); } else if (type == "flag") { const nlohmann::json& flag = Flag(it->at("flag").get<std::string>()); const nlohmann::json& value = it->at("value"); if (JsonType(flag) != JsonType(value)) throw DataLoadError("Gameplay condition value has wrong type"); const std::string op = it->at("comparison").get<std::string>(); if (op != "equal" && op != "notEqual" && (!flag.is_number() || (op != "greater" && op != "greaterOrEqual" && op != "lower" && op != "lowerOrEqual"))) throw DataLoadError("Invalid gameplay flag comparison"); } else throw DataLoadError("Unknown gameplay condition: " + type); } if (definition.contains("actions")) for (nlohmann::json::const_iterator it = definition.at("actions").begin(); it != definition.at("actions").end(); ++it) ValidateAction(*it); if (definition.contains("sequence") && !sequences_.count(definition.at("sequence").get<std::string>())) throw DataLoadError("Gameplay sequence does not exist: " + definition.at("sequence").get<std::string>()); }
void GameplayProgram::ValidateStep(const nlohmann::json& step) const { const std::string type = step.at("type").get<std::string>(); if (type == "action") ValidateAction(step.at("action")); else if (type == "wait") { if (step.at("ticks").get<int>() < 1) throw DataLoadError("Gameplay wait must be positive"); } else { if ((type != "serial" && type != "parallel") || step.at("steps").empty()) throw DataLoadError("Invalid gameplay sequence step"); for (nlohmann::json::const_iterator it = step.at("steps").begin(); it != step.at("steps").end(); ++it) ValidateStep(*it); } }
void GameplayProgram::Execute(const nlohmann::json& action) { ValidateAction(action); const std::string type = action.at("type").get<std::string>(); if (type == "emitEvent") { const std::string id = action.at("event").get<std::string>(); events_.insert(id); if (event_sink_) event_sink_(id); } else { const std::string id = action.at("flag").get<std::string>(); if (type == "setFlag") flags_[id] = action.at("value"); else if (type == "toggleFlag") flags_[id] = !flags_[id].get<bool>(); else flags_[id] = flags_[id].get<double>() + action.at("amount").get<double>(); } }
bool GameplayProgram::Matches(const nlohmann::json& condition) const { const std::string type = condition.at("type").get<std::string>(); if (type == "event") return HasEvent(condition.at("event").get<std::string>()); const nlohmann::json& left = Flag(condition.at("flag").get<std::string>()); const nlohmann::json& right = condition.at("value"); const std::string op = condition.at("comparison").get<std::string>(); if (op == "equal") return left == right; if (op == "notEqual") return left != right; return left.is_number() && right.is_number() && Compare(left.get<double>(), op, right.get<double>()); }
void GameplayProgram::StartSequence(const std::string& id) { std::map<std::string, nlohmann::json>::const_iterator it = sequences_.find(id); if (it == sequences_.end()) throw DataLoadError("Gameplay sequence does not exist: " + id); nlohmann::json root; root["type"] = "serial"; root["steps"] = it->second.at("steps"); running_.push_back(std::shared_ptr<RunningStep>(new RunningStep(root))); }
bool GameplayProgram::Advance(const std::shared_ptr<RunningStep>& step) { if (step->complete) return true; const std::string type = step->definition.at("type").get<std::string>(); if (type == "action") { Execute(step->definition.at("action")); return step->complete = true; } if (type == "wait") { --step->remaining; return step->complete = step->remaining == 0; } if (type == "parallel") { for (size_t i = 0; i < step->children.size(); ++i) Advance(step->children[i]); for (size_t i = 0; i < step->children.size(); ++i) if (!step->children[i]->complete) return false; return step->complete = true; } while (step->index < step->definition.at("steps").size()) { if (step->children.size() <= step->index) step->children.push_back(std::shared_ptr<RunningStep>(new RunningStep(step->definition.at("steps").at(step->index)))); const std::shared_ptr<RunningStep> child = step->children[step->index]; if (!Advance(child)) return false; ++step->index; if (child->definition.at("type") == "wait") return false; } return step->complete = true; }
void GameplayProgram::StepSequences() { for (size_t i = 0; i < running_.size();) { if (Advance(running_[i])) running_.erase(running_.begin() + i); else ++i; } }
