#include "presentation_state.h"
#include "data_loading.h"
#include <algorithm>
#include <cmath>
#include <map>
#include <set>
#include <string>
namespace { void Unique(const nlohmann::json& values, const char* label) { std::set<std::string> ids; for (nlohmann::json::const_iterator it = values.begin(); it != values.end(); ++it) { const std::string id = it->value("id", ""); if (id.empty() || !ids.insert(id).second) throw DataLoadError(std::string("Invalid or duplicate ") + label + ": " + id); } } double Ease(int elapsed, int duration) { if (!duration) return 1; const double p = std::min(1.0, static_cast<double>(elapsed) / duration); return p * p * (3 - 2 * p); } }
PresentationState::PresentationState(const nlohmann::json& definition) : definition_(definition.is_null() ? nlohmann::json::object() : definition) { const nlohmann::json layers = definition_.value("parallaxLayers", nlohmann::json::array()), messages = definition_.value("messages", nlohmann::json::array()), effects = definition_.value("effects", nlohmann::json::array()); Unique(layers, "parallax layer"); Unique(messages, "message"); Unique(effects, "effect"); for (nlohmann::json::const_iterator it = layers.begin(); it != layers.end(); ++it) if (it->value("image", "").empty() || (it->value("plane", "") != "back" && it->value("plane", "") != "front") || !it->contains("factorX") || !it->at("factorX").is_number() || !it->contains("factorY") || !it->at("factorY").is_number() || it->value("opacity", 1.0) < 0 || it->value("opacity", 1.0) > 1) throw DataLoadError("Invalid parallax layer"); for (nlohmann::json::const_iterator it = messages.begin(); it != messages.end(); ++it) if (it->value("text", "").empty() || it->value("durationTicks", 0) < 0) throw DataLoadError("Invalid presentation message"); for (nlohmann::json::const_iterator it = effects.begin(); it != effects.end(); ++it) { const std::string kind = it->value("kind", ""); if ((kind != "fadeIn" && kind != "fadeOut" && kind != "flash") || it->value("color", "").empty() || it->value("durationTicks", 0) < 1) throw DataLoadError("Invalid presentation effect"); } Reset(); }
void PresentationState::Reset() { follow_ = true; camera_x_ = camera_y_ = start_x_ = start_y_ = 0; camera_ticks_ = camera_elapsed_ = message_ticks_ = effect_ticks_ = 0; message_ = effect_ = nlohmann::json(); }
void PresentationState::Step() { if (camera_elapsed_ < camera_ticks_) ++camera_elapsed_; if (!message_.is_null() && message_.value("durationTicks", 0) > 0 && ++message_ticks_ >= message_.value("durationTicks", 0)) message_ = nlohmann::json(); if (!effect_.is_null() && ++effect_ticks_ >= effect_.value("durationTicks", 1)) effect_ = nlohmann::json(); }
void PresentationState::ValidateAction(const nlohmann::json& action) const { const std::string type = action.value("type", ""); if (type == "setCamera") { const std::string mode = action.value("mode", ""); if ((mode != "follow" && mode != "fixed") || action.value("durationTicks", -1) < 0 || (mode == "fixed" && (!action.contains("x") || !action.contains("y")))) throw DataLoadError("Invalid camera presentation action"); return; } if (type == "hideMessage") return; const char* field = type == "showMessage" ? "message" : type == "playEffect" ? "effect" : 0; if (!field) throw DataLoadError("Unregistered presentation action: " + type); const nlohmann::json collection = definition_.value(type == "showMessage" ? "messages" : "effects", nlohmann::json::array()); const std::string id = action.at(field).get<std::string>(); for (nlohmann::json::const_iterator it = collection.begin(); it != collection.end(); ++it) if (it->value("id", "") == id) return; throw DataLoadError(std::string(field) + " does not exist: " + id); }
namespace { void ValidateSteps(const nlohmann::json& steps, const PresentationState& state) { for (nlohmann::json::const_iterator it = steps.begin(); it != steps.end(); ++it) { const std::string type = it->value("type", ""); if (type == "action") { const std::string action_type = it->at("action").value("type", ""); if (action_type == "setCamera" || action_type == "showMessage" || action_type == "hideMessage" || action_type == "playEffect") state.ValidateAction(it->at("action")); } else if (type == "serial" || type == "parallel") ValidateSteps(it->at("steps"), state); } } }
void PresentationState::ValidateProgram(const nlohmann::json& program) const { const nlohmann::json sequences = program.value("sequences", nlohmann::json::array()); for (nlohmann::json::const_iterator it = sequences.begin(); it != sequences.end(); ++it) ValidateSteps(it->at("steps"), *this); }
void PresentationState::Execute(const nlohmann::json& action, double camera_x, double camera_y) { ValidateAction(action); const std::string type = action.value("type", ""); if (type == "setCamera") { follow_ = action.value("mode", "") == "follow"; start_x_ = camera_x; start_y_ = camera_y; camera_x_ = action.value("x", 0.0); camera_y_ = action.value("y", 0.0); camera_ticks_ = action.value("durationTicks", 0); camera_elapsed_ = 0; return; } const nlohmann::json collection = definition_.value(type == "showMessage" ? "messages" : "effects", nlohmann::json::array()); if (type == "hideMessage") { message_ = nlohmann::json(); message_ticks_ = 0; return; } const char* field = type == "showMessage" ? "message" : "effect"; const std::string id = action.at(field).get<std::string>(); for (nlohmann::json::const_iterator it = collection.begin(); it != collection.end(); ++it) if (it->value("id", "") == id) { if (type == "showMessage") { message_ = *it; message_ticks_ = 0; } else { effect_ = *it; effect_ticks_ = 0; } return; } }
bool PresentationState::FollowsPlayer() const { return follow_; }
double PresentationState::CameraX(double follow_x) const { return start_x_ + ((follow_ ? follow_x : camera_x_) - start_x_) * Ease(camera_elapsed_, camera_ticks_); }
double PresentationState::CameraY(double follow_y) const { return start_y_ + ((follow_ ? follow_y : camera_y_) - start_y_) * Ease(camera_elapsed_, camera_ticks_); }
