// Class automatically generated by Dev-C++ New Class wizard

#include "world.h" // class's header file
#include "trigger.h"
#include "enemy.h"
#include "container_utils.h"

// class constructor
World::World()
  : map_width(0), map_height(0), world_tiles(nullptr),
    world_tiles_front(nullptr), current_checkpoint(nullptr),
    target_checkpoints(nullptr), world_image(nullptr)
{
  boundary_tile.SetType(TILE_COL);
}

World::World(const char *file, SoundHandler* sound_handler, bool tileExtractedOption)
  : map_width(0), map_height(0), world_tiles(nullptr),
    world_tiles_front(nullptr), current_checkpoint(nullptr),
    target_checkpoints(nullptr), world_image(nullptr)
{
  boundary_tile.SetType(TILE_COL);

  LoadLevelPackage(file);
  const nlohmann::json& map = GetLevelMap();
  map_width = map.at("width").get<int>();
  map_height = map.at("height").get<int>();
  tileset_width = map.at("tileWidth").get<int>();
  tileset_height = map.at("tileHeight").get<int>();
  const nlohmann::json& tileset = map.at("tileset");
  const std::string tileset_file = tileset.at("image").get<std::string>();
  const nlohmann::json& layers = map.at("layers");
  const nlohmann::json& tiles = layers.at("tiles");
  const nlohmann::json& front_tiles = layers.at("frontTiles");
  const nlohmann::json& collision_tiles = layers.at("collisions");

  printf("Tileset file = %s\n", tileset_file.c_str());

  world_image = al_load_bitmap(tileset_file.c_str());
  if (!world_image) {
    throw DataLoadError(std::string("Cannot load tileset bitmap '") +
                        tileset_file + "'");
  }

  // Set transparent color for tileset
  al_convert_mask_to_alpha(world_image, al_map_rgb(255,0,255));

  tileset_count = tileset.at("tileCount").get<int>();
  tileset_columns = tileset.at("columns").get<int>();
  tileset_tile_width = map.at("tileWidth").get<int>();
  tileset_tile_height = map.at("tileHeight").get<int>();

  printf("Tileset count = %d\nTileset columns = %d\nTile width = %d\nTile height = %d\n", tileset_count, tileset_columns, tileset_tile_width, tileset_tile_height);
  
  // Initialize world    
  world_tiles = new Tile**[map_width];
  world_tiles_front = new Tile**[map_width];
  
  for (int x = 0 ; x < map_width ; x++ ) {
      world_tiles[x] = new Tile*[map_height];
      world_tiles_front[x] = new Tile*[map_height];
      for (int y = 0 ; y < map_height ; y++ ) {
        world_tiles[x][y] = new Tile();
        world_tiles_front[x][y] = new Tile();
      }
  }

  // First initialize tiles
  // Tile properties is a layer of same size as tiles, so we can reuse the for stament
  // for both of them. REVISIT: add check to verify they have same size?
  for (std::size_t index = 0; index < tiles.size(); ++index) {
    const int x = static_cast<int>(index % map_width);
    const int y = static_cast<int>(index / map_width);
    const int tile_gid = tiles[index].get<int>();
    const int front_gid = front_tiles[index].get<int>();
    const int collision_gid = collision_tiles[index].get<int>();
    int tile_id       = tile_gid != 0 ? tile_gid - 1 : 0;
    int tile_front_id = front_gid != 0 ? front_gid - 1 : 0;
    int tile_prop     = collision_gid != 0 ? collision_gid - 1 : 0;
    // Save the id of the tile aswell as the coordinates in the tileset bitmap
    // Preserve the TMX GID as the presence marker: 0 means empty while GID 1
    // is the first (zero-based index 0) tile in the tileset.
    world_tiles[x][y]->SetValue(tile_gid);
    world_tiles[x][y]->SetType(tile_prop);
    world_tiles[x][y]->SetLeftUpX((tile_id % tileset_columns) * tileset_width);
    world_tiles[x][y]->SetLeftUpY(ceil(tile_id/tileset_columns)*tileset_height);
    world_tiles[x][y]->SetRightDownX((tile_id % tileset_columns) * tileset_width + tileset_width);
    world_tiles[x][y]->SetRightDownY(ceil((tile_id/tileset_columns))*tileset_height + tileset_height);
    // Same for tiles in front
    world_tiles_front[x][y]->SetValue(front_gid);
    world_tiles_front[x][y]->SetType(tile_prop);
    world_tiles_front[x][y]->SetLeftUpX((tile_front_id % tileset_columns) * tileset_width);
    world_tiles_front[x][y]->SetLeftUpY(ceil(tile_front_id/tileset_columns)*tileset_height);
    world_tiles_front[x][y]->SetRightDownX((tile_front_id % tileset_columns) * tileset_width + tileset_width);
    world_tiles_front[x][y]->SetRightDownY(ceil((tile_front_id/tileset_columns))*tileset_height + tileset_height);
  }

  // Read platforms
  this->InitializePlatforms("platforms");
  // Read items
  this->InitializeItems("items", sound_handler);
  // Read dynamic background objects
  this->InitializeDynamicBackObjects("backgroundObjects");
  // Read blocks
  this->InitializeBlocks("blocks");
  // Read hazards
  this->InitializeHazards("hazards");
  // Read checkpoints
  this->InitializeCheckpoints("checkpoints");
  // Read lasers
  this->InitializeLasers("lasers");
  // Read triggers
  this->InitializeTriggers("triggers");
  // Read enemies
  this->InitializeEnemies("enemies");
  // Read camera views
  this->InitializeCameraViews("cameraViews");

  shoot_exists = false;
  bomb_exists = false;
}

// class destructor
World::~World()
{
  for (int x = 0; x < map_width; ++x) {
    for (int y = 0; y < map_height; ++y) {
      delete world_tiles[x][y];
      delete world_tiles_front[x][y];
    }
    delete[] world_tiles[x];
    delete[] world_tiles_front[x];
  }
  delete[] world_tiles;
  delete[] world_tiles_front;
  if (world_image) {
    al_destroy_bitmap(world_image);
  }

  // Destroy platforms
  for (vector<Platform*>::iterator it = platforms.begin() ; it != platforms.end(); ++it) {
      delete *it;
  }
  for (list<Object*>::iterator it = objects.begin() ; it != objects.end(); ++it) {
      delete *it;
  }
  for (list<Object*>::iterator it = back_objects.begin() ; it != back_objects.end(); ++it) {
      delete *it;
  }
  for (list<Block*>::iterator it = blocks.begin() ; it != blocks.end(); ++it) {
      delete *it;
  }
  for (list<Checkpoint*>::iterator it = checkpoints.begin() ; it != checkpoints.end(); ++it) {
      delete *it;
  }
  for (list<Trigger*>::iterator it = triggers.begin() ; it != triggers.end(); ++it) {
      delete *it;
  }
  for (vector<Character*>::iterator it = enemies.begin() ; it != enemies.end(); ++it) {
      delete *it;
  }
  for (vector<CameraView*>::iterator it = camera_views.begin() ; it != camera_views.end(); ++it) {
      delete *it;
  }
}

void World::InitializePlatforms(const char* file) {
  int platform_id;
  int plat_ini_x;
  int plat_ini_y;
  int plat_width;
  int plat_height;
  int plat_visible;
  int plat_recursive;
  int plat_one_use;
  int plat_ini_state;
  int action_direction;
  int action_desp;
  int action_wait;
  float action_speed;
  int action_cond;
  int num_actions;

  printf("---------------------------\n");
  printf("| Initializing platforms  |\n");
  printf("---------------------------\n");

  const nlohmann::json& platform_data = GetLevelEntities("platforms");
  for (nlohmann::json::const_iterator plat = platform_data.begin();
       plat != platform_data.end(); ++plat) {
    const nlohmann::json& plat_attrs = plat->at("attributes");
    // First read attributes
    platform_id = plat->at("id").get<int>();
    printf("Platform id = %d\n", platform_id);

    plat_ini_x = plat_attrs.at("ini_x").get<int>();
    plat_ini_y = plat_attrs.at("ini_y").get<int>();
    plat_width = plat_attrs.at("width").get<int>();
    plat_height = plat_attrs.at("height").get<int>();
    plat_visible = plat_attrs.at("visible").get<int>();
    plat_recursive = plat_attrs.at("recursive").get<int>();
    plat_one_use = plat_attrs.at("one_use").get<int>();
    const std::string initial_state = plat_attrs.at("ini_state").get<std::string>();
    plat_ini_state = initial_state == "stop" ?
                       OBJ_STATE_STOP :
                       OBJ_STATE_MOVING;
    const std::string definition_file = plat_attrs.at("definition").get<std::string>();
    printf(" - File = %s\n", definition_file.c_str());
    printf(" - ini_x = %d\n", plat_ini_x);
    printf(" - ini_y = %d\n", plat_ini_y);
    printf(" - width = %d\n", plat_width);
    printf(" - height = %d\n", plat_height);
    printf(" - visible = %d\n", plat_visible);
    printf(" - recursive = %d\n", plat_recursive);
    printf(" - one_use = %d\n", plat_one_use);
    printf(" - ini_state = %s\n", initial_state.c_str());

    // Create platform
    Platform* world_platform = new Platform(definition_file.c_str(),
                                            platform_id,
                                            plat_ini_state,
                                            plat_ini_x,
                                            plat_ini_y,
                                            plat_width,
                                            plat_height,
                                            plat_visible,
                                            plat_recursive,
                                            plat_one_use);

    printf(" - actions:\n");
    num_actions = 0;
    // Second, get actions
    const nlohmann::json& action_value = plat->at("actions").at("action");
    nlohmann::json actions = action_value.is_array()
                                 ? action_value
                                 : nlohmann::json::array({action_value});
    for (nlohmann::json::const_iterator action = actions.begin();
         action != actions.end(); ++action) {
      printf("\t - action %d:\n", num_actions);
      const std::string action_direction_name = action->at("direction").get<std::string>();
      if (action_direction_name == "stop") {
        action_direction = OBJ_DIR_STOP;
      } else if (action_direction_name == "right") {
        action_direction = OBJ_DIR_RIGHT;
      } else if (action_direction_name == "left") {
        action_direction = OBJ_DIR_LEFT;
      } else if (action_direction_name == "up") {
        action_direction = OBJ_DIR_UP;
      } else if (action_direction_name == "down") {
        action_direction = OBJ_DIR_DOWN;
      } else {
        throw DataLoadError(std::string("Invalid '") + file +
                            "': incorrect platform action direction");
      }
      action_desp = action->at("desp").get<int>();
      action_wait = action->at("wait").get<int>();
      action_speed = action->at("speed").get<float>();
      action_cond = action->at("cond").get<int>();
      printf("\t\t - direction=%s\n", action_direction_name.c_str());
      printf("\t\t - desp=%d\n", action_desp);
      printf("\t\t - wait=%d\n", action_wait);
      printf("\t\t - speed=%f\n", action_speed);
      printf("\t\t - cond=%d\n", action_cond);

      world_platform->AddAction(action_direction,
                                action_desp,
                                action_wait,
                                action_speed,
                                action_cond);  // REVISIT: no actions for platforms yet
      num_actions++;
    }
    platforms.push_back(world_platform);

  }  

  printf("---------------------------\n");
}

void World::InitializeHazards(const char* file) {
  int   hazard_id;
  int   hazard_ini_x;
  int   hazard_ini_y;
  int   hazard_width;
  int   hazard_height;
  bool  hazard_trigger;
  bool  hazard_stop_inactive;
  int   action_direction;
  int   action_desp;
  int   action_wait;
  float action_speed;
  bool  action_deactivate;
  int   action_cond;
  int   num_actions;  

  printf("---------------------------\n");
  printf("| Initializing hazards    |\n");
  printf("---------------------------\n");

  const nlohmann::json& hazard_data = GetLevelEntities("hazards");
  for (nlohmann::json::const_iterator hazard = hazard_data.begin();
       hazard != hazard_data.end(); ++hazard) {
    const nlohmann::json& hazard_attrs = hazard->at("attributes");
    // First read attributes
    hazard_id = hazard->at("id").get<int>();
    printf("Hazard id = %d\n", hazard_id);

    hazard_ini_x = hazard_attrs.at("ini_x").get<int>();
    hazard_ini_y = hazard_attrs.at("ini_y").get<int>();
    hazard_width = hazard_attrs.at("width").get<int>();
    hazard_height = hazard_attrs.at("height").get<int>();
    hazard_trigger = hazard_attrs.at("trigger").get<int>() != 0;
    hazard_stop_inactive = hazard_attrs.at("stop_inactive").get<int>() != 0;


    const std::string definition_file = hazard_attrs.at("definition").get<std::string>();
    printf(" - File = %s\n", definition_file.c_str());
    printf(" - ini_x = %d\n",         hazard_ini_x);
    printf(" - ini_y = %d\n",         hazard_ini_y);
    printf(" - width = %d\n",         hazard_width);
    printf(" - height = %d\n",        hazard_height);
    printf(" - trigger = %d\n",       hazard_trigger);
    printf(" - stop_inactive = %d\n", hazard_stop_inactive);

    // Create hazard
    Hazard* world_hazard = new Hazard(definition_file.c_str(),
                                      hazard_id,
                                      hazard_ini_x,
                                      hazard_ini_y,
                                      hazard_width,
                                      hazard_height,
                                      hazard_trigger,
                                      hazard_stop_inactive);

    printf(" - actions:\n");
    num_actions = 0;
    // Second, get actions
    const nlohmann::json& action_value = hazard->at("actions").at("action");
    nlohmann::json actions = action_value.is_array()
                                 ? action_value
                                 : nlohmann::json::array({action_value});
    for (nlohmann::json::const_iterator action = actions.begin();
         action != actions.end(); ++action) {
      printf("\t - action %d:\n", num_actions);
      action_deactivate = false;
      const std::string action_direction_name = action->at("direction").get<std::string>();
      if (action_direction_name == "stop") {
        action_direction = OBJ_DIR_STOP;
      } else if (action_direction_name == "right") {
        action_direction = OBJ_DIR_RIGHT;
      } else if (action_direction_name == "left") {
        action_direction = OBJ_DIR_LEFT;
      } else if (action_direction_name == "up") {
        action_direction = OBJ_DIR_UP;
      } else if (action_direction_name == "down") {
        action_direction = OBJ_DIR_DOWN;
      } else if (action_direction_name == "deactivate") {
        action_direction = OBJ_DIR_STOP;
        action_deactivate = true;
      } else {
        throw DataLoadError(std::string("Invalid '") + file +
                            "': incorrect hazard action direction");
      }
      action_desp = action->at("desp").get<int>();
      action_wait = action->at("wait").get<int>();
      action_speed = action->at("speed").get<float>();
      action_cond = action->at("cond").get<int>();
      printf("\t\t - direction=%s\n", action_direction_name.c_str());
      printf("\t\t - deactivate=%d\n", (int)action_deactivate);
      printf("\t\t - desp=%d\n", action_desp);
      printf("\t\t - wait=%d\n", action_wait);
      printf("\t\t - speed=%f\n", action_speed);
      printf("\t\t - wait=%d\n", action_cond);

      world_hazard->AddAction(action_direction,
                              action_desp,
                              action_wait,
                              action_speed,
                              !action_deactivate,
                              action_cond);
      num_actions++;
    }
    objects.push_back(world_hazard);

  }  

  printf("---------------------------\n");
}

void World::InitializeItems(const char* file, SoundHandler* sound_handler) {
  int item_id;
  int item_ini_x;
  int item_ini_y;
  int item_width;
  int item_height;  

  printf("---------------------------\n");
  printf("| Initializing items      |\n");
  printf("---------------------------\n");

  const nlohmann::json& item_data = GetLevelEntities("items");
  for (nlohmann::json::const_iterator item = item_data.begin();
       item != item_data.end(); ++item) {
    const nlohmann::json& item_attrs = item->at("attributes");
    // First read attributes
    item_id = item->at("id").get<int>();
    printf("Item id = %d\n", item_id);

    item_ini_x  = item_attrs.at("ini_x").get<int>();
    item_ini_y  = item_attrs.at("ini_y").get<int>();
    item_width  = item_attrs.at("width").get<int>();
    item_height = item_attrs.at("height").get<int>();

    const std::string definition_file = item_attrs.at("definition").get<std::string>();
    printf(" - File = %s\n", definition_file.c_str());
    printf(" - ini_x = %d\n", item_ini_x);
    printf(" - ini_y = %d\n", item_ini_y);
    printf(" - width = %d\n", item_width);
    printf(" - height = %d\n", item_height);

    // Create item
    Item* world_item = new Item(item_id);
    world_item->Init(definition_file.c_str(),
                     item_ini_x, item_ini_y,
                     item_width, item_height,
                     true, true,
                     OBJ_STATE_STOP, OBJ_DIR_STOP,
                     0.1, 3.0, 1.0,
                     0.1, 3.0, 1.0);
    world_item->RegisterSoundHandler(sound_handler);

    objects.push_back(world_item);
  }  

  printf("---------------------------\n");
}

void World::InitializeDynamicBackObjects(const char* file) {
  int dyn_obj_id;
  int dyn_obj_ini_x;
  int dyn_obj_ini_y;
  int dyn_obj_width;
  int dyn_obj_height;
  int dyn_obj_skip_num_anims;

  printf("------------------------------------------\n");
  printf("| Initializing dynamic backgound objects |\n");
  printf("------------------------------------------\n");

  const nlohmann::json& background_data = GetLevelEntities("backgroundObjects");
  for (nlohmann::json::const_iterator dyn_obj = background_data.begin();
       dyn_obj != background_data.end(); ++dyn_obj) {
    const nlohmann::json& dyn_obj_attrs = dyn_obj->at("attributes");
    // First read attributes
    dyn_obj_id = dyn_obj->at("id").get<int>();
    printf("Dynamic object id = %d\n", dyn_obj_id);

    dyn_obj_ini_x = dyn_obj_attrs.at("ini_x").get<int>();
    dyn_obj_ini_y = dyn_obj_attrs.at("ini_y").get<int>();
    dyn_obj_width = dyn_obj_attrs.at("width").get<int>();
    dyn_obj_height = dyn_obj_attrs.at("height").get<int>();
    dyn_obj_skip_num_anims = dyn_obj_attrs.at("skip_num_anims").get<int>();

    const std::string definition_file = dyn_obj_attrs.at("definition").get<std::string>();
    printf(" - File = %s\n", definition_file.c_str());
    printf(" - ini_x = %d\n", dyn_obj_ini_x);
    printf(" - ini_y = %d\n", dyn_obj_ini_y);
    printf(" - width = %d\n", dyn_obj_width);
    printf(" - height = %d\n", dyn_obj_height);
    printf(" - skip_anims = %d\n", dyn_obj_skip_num_anims);

    // Create dyn_obj
    StaticObject* world_dyn_obj = new StaticObject(dyn_obj_id);
    world_dyn_obj->Init(definition_file.c_str(),
                        dyn_obj_ini_x, dyn_obj_ini_y,
                        dyn_obj_width, dyn_obj_height,
                        dyn_obj_skip_num_anims);

    back_objects.push_back(world_dyn_obj);
  }  

  printf("---------------------------\n");
}

void World::InitializeBlocks(const char* file) {
  int  block_id;
  int  block_ini_x;
  int  block_ini_y;
  int  block_width;
  int  block_height;
  bool block_exploits;

  printf("------------------------------\n");
  printf("| Initializing block objects |\n");
  printf("-----------------------------\n");

  const nlohmann::json& block_data = GetLevelEntities("blocks");
  for (nlohmann::json::const_iterator block = block_data.begin();
       block != block_data.end(); ++block) {
    const nlohmann::json& block_attrs = block->at("attributes");
    // First read attributes
    block_id = block->at("id").get<int>();
    printf("Block object id = %d\n", block_id);

    block_ini_x = block_attrs.at("ini_x").get<int>();
    block_ini_y = block_attrs.at("ini_y").get<int>();
    block_width = block_attrs.at("width").get<int>();
    block_height = block_attrs.at("height").get<int>();
    block_exploits = block_attrs.at("exploits").get<int>() != 0;

    const std::string definition_file = block_attrs.at("definition").get<std::string>();
    printf(" - File = %s\n", definition_file.c_str());
    printf(" - ini_x = %d\n", block_ini_x);
    printf(" - ini_y = %d\n", block_ini_y);
    printf(" - width = %d\n", block_width);
    printf(" - height = %d\n", block_height);
    printf(" - exploits = %d\n", (int)block_exploits);

    // Create block
    Block* world_block = new Block(block_id);
    world_block->Init(definition_file.c_str(),
                      block_ini_x, block_ini_y,
                      block_width, block_height,
                      block_exploits);

    blocks.push_back(world_block);
  }  

  printf("---------------------------\n");
}

void World::InitializeCheckpoints(const char* file) {
  int chk_id;
  int chk_x;
  int chk_y;
  int chk_width;
  int chk_height;
  int pl_x;
  int pl_y;
  int pl_face;
  vector<vector<int> > nxt_chks;

  printf("------------------------------------\n");
  printf("| Initializing checkpoints objects |\n");
  printf("------------------------------------\n");

  const nlohmann::json& checkpoint_data = GetLevelEntities("checkpoints");
  if (checkpoint_data.empty()) {
    throw DataLoadError(std::string("Invalid '") + file +
                        "': at least one checkpoint is required");
  }
 
  for (nlohmann::json::const_iterator chk = checkpoint_data.begin();
       chk != checkpoint_data.end(); ++chk) {
    // First read attributes
    chk_id = chk->at("id").get<int>();
    printf("Checkpoint id = %d\n", chk_id);
    
    chk_x      = chk->at("chk_x").get<int>();
    chk_y      = chk->at("chk_y").get<int>();
    chk_width  = chk->at("chk_width").get<int>();
    chk_height = chk->at("chk_height").get<int>();
    pl_x       = chk->at("pl_x").get<int>();
    pl_y       = chk->at("pl_y").get<int>();
    const std::string player_face = chk->at("pl_face").get<std::string>();
    if (player_face == "right") {
      pl_face = CHAR_DIR_RIGHT;
    } else if (player_face == "left") {
      pl_face = CHAR_DIR_LEFT;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect player direction for checkpoint " +
                          std::to_string(chk_id));
    }

    vector<int> nxt_chks_int =
        chk->at("nxt_chks").get<vector<int> >();
    nxt_chks.push_back(nxt_chks_int);

    printf(" - chk_x = %d\n", chk_x);
    printf(" - chk_y = %d\n", chk_y);
    printf(" - chk_width = %d\n", chk_width);
    printf(" - chk_height = %d\n", chk_height);
    printf(" - pl_x = %d\n", pl_x);
    printf(" - pl_y = %d\n", pl_y);
    printf(" - pl_face = %d\n", pl_face);
    printf(" - nxt_chks=");
    for(vector<int>::iterator it = nxt_chks_int.begin(); it != nxt_chks_int.end(); it++) {
      printf("%d ", *it);
    }
    printf("\n");

    // Create checkpoint
    Checkpoint* world_chk = new Checkpoint(chk_id, chk_x, chk_y, chk_width, chk_height, pl_x, pl_y, pl_face);
    checkpoints.push_back(world_chk);
  }  

  int num_chk = 0;  
  // Once all checkpoints are read, the proceed to link them based on nxt_chks
  for (list<Checkpoint*>::iterator it1 = checkpoints.begin(); it1 != checkpoints.end(); it1++) {
    Checkpoint* chk_orig = *it1;
    // Search for all the checkpoints to be linked
    for (vector<int>::iterator it2 = nxt_chks[num_chk].begin(); it2 != nxt_chks[num_chk].end(); it2++) {
      int num_chk_to_link = *it2;
      // Search this id in the checkpoints list and get the pointer
      bool found = false;
      for (list<Checkpoint*>:: iterator it3 = checkpoints.begin(); it3 != checkpoints.end(); it3++) {
         Checkpoint* chk_to_link = *it3;
         if (chk_to_link->GetChkId() == num_chk_to_link) {
           chk_orig->AddNextCheckpoint(chk_to_link);
           found = true;
         }
      }
      // If not found then return an error
      if (!found) {
        throw DataLoadError(std::string("Invalid '") + file +
                            "': broken checkpoint link for checkpoint " +
                            std::to_string(num_chk));
      }
    }
    num_chk++;
  }

  current_checkpoint = *(checkpoints.begin());
  target_checkpoints = current_checkpoint->GetNextCheckpoints();

  printf("---------------------------\n");
}


void World::InitializeTriggers(const char* file) {
  int  trig_id;
  int  trig_x;
  int  trig_y;
  int  trig_width;
  int  trig_height;
  bool trig_recursive;
  int  trig_action;
  int  trig_face;
  int  target_type;
  int  target_id;
  int  target_delay;
  bool target_trigger;
  bool target_trigger_cond;
  int  num_targets;

  printf("---------------------------\n");
  printf("| Initializing triggers   |\n");
  printf("---------------------------\n");

  const nlohmann::json& trigger_data = GetLevelEntities("triggers");
  for (nlohmann::json::const_iterator trig = trigger_data.begin();
       trig != trigger_data.end(); ++trig) {
    const nlohmann::json& trig_attrs = trig->at("attributes");
    // First read attributes
    trig_id = trig->at("id").get<int>();
    printf("Trigger id = %d\n", trig_id);

    trig_x = trig_attrs.at("x").get<int>();
    trig_y = trig_attrs.at("y").get<int>();
    trig_width = trig_attrs.at("width").get<int>();
    trig_height = trig_attrs.at("height").get<int>();
    trig_recursive = trig_attrs.at("recursive").get<int>() != 0;
    const std::string trigger_action = trig_attrs.at("action").get<std::string>();
    if (trigger_action == "enters") {
      trig_action = ACTION_EVENT_ENTERS;
    } else if (trigger_action == "stays") {
      trig_action = ACTION_EVENT_STAYS;
    } else if (trigger_action == "exits") {
      trig_action = ACTION_EVENT_EXITS;
    } else if (trigger_action == "hits") {
      trig_action = ACTION_EVENT_HITS;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect action for trigger " +
                          std::to_string(trig_id));
    }

    const std::string trigger_face = trig_attrs.at("face").get<std::string>();
    if (trigger_face == "any") {
      trig_face = ACTION_FACE_ANY;
    } else if (trigger_face == "right") {
      trig_face = ACTION_FACE_RIGHT;
    } else if (trigger_face == "left") {
      trig_face = ACTION_FACE_LEFT;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect face for trigger " +
                          std::to_string(trig_id));
    }
    
    printf(" - x = %d\n",      trig_x);
    printf(" - y = %d\n",      trig_y);
    printf(" - width = %d\n",  trig_width);
    printf(" - height = %d\n", trig_height);
    printf(" - recursive = %d\n", trig_recursive);
    printf(" - action = %d\n", trig_action);
    printf(" - face = %d\n",   trig_face);    

    // Create platform
    Trigger* world_trigger = new Trigger(trig_id,
                                         trig_x,
                                         trig_y,
                                         trig_width,
                                         trig_height,
                                         trig_action,
                                         trig_face,
                                         trig_recursive);

    printf(" - targets:\n");
    num_targets = 0;
    // Second, get targets
    const nlohmann::json& target_value = trig->at("targets").at("target");
    nlohmann::json targets = target_value.is_array()
                                 ? target_value
                                 : nlohmann::json::array({target_value});
    for (nlohmann::json::const_iterator target = targets.begin();
         target != targets.end(); ++target) {
      printf("\t - target %d:\n", num_targets);
      const std::string target_type_name = target->at("type").get<std::string>();
      if (target_type_name == "platform") {
        target_type = OBJ_PLATFORM;
      } else if (target_type_name == "laser") {
        target_type = OBJ_LASER;
      } else if (target_type_name == "hazard") {
        target_type = OBJ_HAZARD;
      } else {
        throw DataLoadError(std::string("Invalid '") + file +
                            "': incorrect target type for trigger " +
                            std::to_string(trig_id));
      }
      target_id = target->at("id").get<int>();
      target_delay = target->at("delay").get<int>();
      target_trigger = target->at("trigger").get<int>() != 0;
      target_trigger_cond = target->at("trigger_cond").get<int>() != 0;
      printf("\t\t - type=%s\n", target_type_name.c_str());
      printf("\t\t - id=%d\n", target_id);
      printf("\t\t - delay=%d\n", target_delay);
      printf("\t\t - trigger=%d\n", target_trigger);
      printf("\t\t - trigger_cond=%d\n", target_trigger_cond);

      Object* target_ptr;
      if (target_type == OBJ_PLATFORM)
        target_ptr = (Object*)GetPlatform(target_id);
      else if (target_type == OBJ_LASER)
        target_ptr = (Object*)GetLaser(target_id);
      else
        target_ptr = (Object*)GetHazard(target_id);

      if (target_ptr == nullptr) {
        throw DataLoadError(std::string("Invalid '") + file +
                            "': trigger " + std::to_string(trig_id) +
                            " references a missing target");
      }

      world_trigger->AddTarget(target_ptr, target_delay, target_trigger, target_trigger_cond);

      num_targets++;
    }

    triggers.push_back(world_trigger);

  }  

  printf("---------------------------\n");
}

void World::InitializeLasers(const char* file) {
  int   laser_id;
  int   laser_x;
  int   laser_y;
  int   laser_bb_x;
  int   laser_bb_y;
  int   laser_bb_width;
  int   laser_bb_height;
  int   laser_type;
  float laser_speed;
  bool  laser_onehot;
  int   laser_direction;
  int   laser_default_trigger;

  printf("------------------------------\n");
  printf("| Initializing laser objects |\n");
  printf("------------------------------\n");

  const nlohmann::json& laser_data = GetLevelEntities("lasers");
  for (nlohmann::json::const_iterator laser = laser_data.begin();
       laser != laser_data.end(); ++laser) {
    // First read attributes
    laser_id = laser->at("id").get<int>();
    printf("Laser id = %d\n", laser_id);
    
    laser_x = laser->at("x").get<int>();
    laser_y = laser->at("y").get<int>();
    laser_bb_x = laser->at("bb_x").get<int>();
    laser_bb_y = laser->at("bb_y").get<int>();
    laser_bb_width = laser->at("bb_width").get<int>();
    laser_bb_height = laser->at("bb_height").get<int>();
    const std::string laser_type_name = laser->at("type").get<std::string>();
    if (laser_type_name == "horizontal") {
      laser_type = LASER_TYPE_HORIZONTAL;
    } else if (laser_type_name == "vertical") {
      laser_type = LASER_TYPE_VERTICAL;
    } else if (laser_type_name == "diagonal") {
      laser_type = LASER_TYPE_DIAGONAL;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect type for laser " +
                          std::to_string(laser_id));
    }
    laser_speed = laser->at("speed").get<float>();
    laser_onehot = laser->at("recursive").get<int>() == 0;
    laser_default_trigger = laser->at("default_trigger").get<int>();
    const std::string laser_direction_name = laser->at("direction").get<std::string>();
    if (laser_direction_name == "right") {
      laser_direction = OBJ_DIR_RIGHT;
    } else if (laser_direction_name == "left") {
      laser_direction = OBJ_DIR_LEFT;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect direction for laser " +
                          std::to_string(laser_id));
    }
    printf(" - x = %d\n", laser_x);
    printf(" - y = %d\n", laser_y);
    printf(" - bb_x = %d\n", laser_bb_x);
    printf(" - bb_y = %d\n", laser_bb_y);
    printf(" - bb_width = %d\n", laser_bb_width);
    printf(" - bb_height = %d\n", laser_bb_height);
    printf(" - type = %d\n", laser_type);
    printf(" - onehot = %d\n", laser_onehot);
    printf(" - direction = %d\n", laser_direction);
    printf(" - speed = %f\n", laser_speed);
    printf(" - default_trigger = %d\n", laser_default_trigger);

    // Create checkpoint
    const std::string definition_file = laser->at("definition").get<std::string>();
    Laser* world_laser = new Laser(definition_file.c_str(),
                                   laser_id,
                                   laser_x, laser_y,
                                   laser_bb_x, laser_bb_y,
                                   laser_bb_width, laser_bb_height,
                                   laser_type, laser_onehot, laser_speed, laser_direction, laser_default_trigger);


    objects.push_back(world_laser);
  }  

  printf("---------------------------\n");
}

void World::InitializeEnemies(const char* file) {
  int   enemy_id;
  int   enemy_x;
  int   enemy_y;
  int   enemy_bb_x;
  int   enemy_bb_y;  
  int   enemy_bb_width;
  int   enemy_bb_height;
  int   enemy_direction;
  float enemy_speed_x;
  float enemy_speed_y;
  int   enemy_ia_type;
  int   enemy_ia_random;
  int   enemy_ia_randomness;
  int   enemy_ia_block_steps;
  int   enemy_ia_orig_x;
  int   enemy_ia_orig_y;
  int   enemy_ia_limit_x;
  int   enemy_ia_limit_y;

  printf("------------------------------------\n");
  printf("| Initializing enemies             |\n");
  printf("------------------------------------\n");

  const nlohmann::json& enemy_data = GetLevelEntities("enemies");
  for (nlohmann::json::const_iterator enemy = enemy_data.begin();
       enemy != enemy_data.end(); ++enemy) {
    // First read attributes
    enemy_id = enemy->at("id").get<int>();
    printf("Enemy id = %d\n", enemy_id);
    
    enemy_x = enemy->at("x").get<int>();
    enemy_y = enemy->at("y").get<int>();
    enemy_bb_x = enemy->at("bb_x").get<int>();
    enemy_bb_y = enemy->at("bb_y").get<int>();
    enemy_bb_width = enemy->at("bb_width").get<int>();
    enemy_bb_height = enemy->at("bb_height").get<int>();
    enemy_speed_x = enemy->at("speed_x").get<float>();
    enemy_speed_y = enemy->at("speed_y").get<float>();
    const std::string enemy_direction_name = enemy->at("direction").get<std::string>();
    if (enemy_direction_name == "right") {
      enemy_direction = CHAR_DIR_RIGHT;
    } else if (enemy_direction_name == "left") {
      enemy_direction = CHAR_DIR_LEFT;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect direction for enemy " +
                          std::to_string(enemy_id));
    }
    const std::string ai_type = enemy->at("ia_type").get<std::string>();
    if (ai_type == "walker") {
      enemy_ia_type = ENEMY_IA_WALKER;
    } else if (ai_type == "chaser") {
      enemy_ia_type = ENEMY_IA_CHASER;
    } else {
      throw DataLoadError(std::string("Invalid '") + file +
                          "': incorrect AI type for enemy " +
                          std::to_string(enemy_id));
    }
    enemy_ia_random = enemy->at("ia_random").get<int>() != 0;
    enemy_ia_randomness = enemy->at("ia_randomness").get<int>();
    enemy_ia_block_steps = enemy->at("ia_block_steps").get<int>();
    enemy_ia_orig_x = enemy->at("ia_orig_x").get<int>();
    enemy_ia_orig_y = enemy->at("ia_orig_y").get<int>();
    enemy_ia_limit_x = enemy->at("ia_limit_x").get<int>();
    enemy_ia_limit_y = enemy->at("ia_limit_y").get<int>();

    const std::string definition_file = enemy->at("definition").get<std::string>();
    printf(" - file = %s\n", definition_file.c_str());
    printf(" - x = %d\n", enemy_x);
    printf(" - y = %d\n", enemy_y);
    printf(" - bb_x = %d\n", enemy_bb_x);
    printf(" - bb_y = %d\n", enemy_bb_y);
    printf(" - bb_width = %d\n", enemy_bb_width);
    printf(" - bb_height = %d\n", enemy_bb_height);
    printf(" - speed_x=%f\n", enemy_speed_x);
    printf(" - speed_y=%f\n", enemy_speed_y);
    printf(" - direction = %d\n", enemy_direction);
    printf(" - ia_type = %d\n", enemy_ia_type);
    printf(" - ia_random = %d\n", enemy_ia_random);
    printf(" - ia_randomness = %d\n", enemy_ia_randomness);
    printf(" - ia_block_steps = %d\n", enemy_ia_block_steps);
    printf(" - ia_orig_x = %d\n", enemy_ia_orig_x);
    printf(" - ia_orig_y = %d\n", enemy_ia_orig_y);
    printf(" - ia_limit_x = %d\n", enemy_ia_limit_x);
    printf(" - ia_limit_y = %d\n", enemy_ia_limit_y);

    // Create enemy
    Enemy* world_enemy = new Enemy(definition_file.c_str(),
                                   enemy_id,
                                   enemy_x, enemy_y,
                                   enemy_bb_x, enemy_bb_y, enemy_bb_width, enemy_bb_height,
                                   enemy_direction, enemy_speed_x, enemy_speed_y,
                                   enemy_ia_type, enemy_ia_random, enemy_ia_randomness, enemy_ia_block_steps,
                                   enemy_ia_orig_x, enemy_ia_orig_y, enemy_ia_limit_x, enemy_ia_limit_y);
    enemies.push_back(world_enemy);
  }  

  printf("---------------------------\n");
}

void World::InitializeCameraViews(const char* file) {
  int view_id;
  int left_up_x;
  int left_up_y;
  int right_down_x;
  int right_down_y;

  printf("------------------------------------\n");
  printf("| Initializing camera views        |\n");
  printf("------------------------------------\n");

  const nlohmann::json& view_data = GetLevelEntities("cameraViews");
  for (nlohmann::json::const_iterator view = view_data.begin();
       view != view_data.end(); ++view) {
    // First read attributes
    view_id = view->at("id").get<int>();
    printf("View id = %d\n", view_id);
    
    left_up_x = view->at("left_up_x").get<int>();
    left_up_y = view->at("left_up_y").get<int>();
    right_down_x = view->at("right_down_x").get<int>();
    right_down_y = view->at("right_down_y").get<int>();

    printf(" - left_up_x = %d\n", left_up_x);
    printf(" - left_up_y = %d\n", left_up_y);
    printf(" - right_down_x = %d\n", right_down_x);
    printf(" - right_down_y = %d\n", right_down_y);

    // Create camera view
    CameraView* world_view = new CameraView(view_id, left_up_x, left_up_y, right_down_x, right_down_y);
    camera_views.push_back(world_view);
  }

  printf("---------------------------\n");
}

int World::GetMapWidth() {
   return map_width;
}

int World::GetMapHeight() {
  return map_height;
}

int World::GetTilesetWidth() {
  return tileset_width;
}

int World::GetTilesetHeight() {
  return tileset_height;
}

int World::GetTilesetCount() {
  return tileset_count;
}

int World::GetTilesetColumns() {
  return tileset_columns;
}

int World::GetTilesetTileWidth() {
  return tileset_tile_width;
}

int World::GetTilesetTileHeight() {
  return tileset_tile_height;
}

Tile* World::GetTile(int x, int y) {
  if (!IsTileIndexInBounds(x, y, map_width, map_height)) {
    return &empty_tile;
  }
  return world_tiles[x][y];
}

Tile* World::GetTileFront(int x, int y) {
  if (!IsTileIndexInBounds(x, y, map_width, map_height)) {
    return &empty_tile;
  }
  return world_tiles_front[x][y];
}

bool World::IsTileCollisionable(int x, int y) {
  if (!IsTileIndexInBounds(x, y, map_width, map_height)) {
    return true;
  }
  return (world_tiles[x][y]->GetType() == TILE_COL);
}

bool World::IsTileCollisionableDown(int x, int y) {
  if (!IsTileIndexInBounds(x, y, map_width, map_height)) {
    return true;
  }
  return ((world_tiles[x][y]->GetType() == TILE_COL) ||
          (world_tiles[x][y]->GetType() == TILE_COL_DOWN) ||
          (world_tiles[x][y]->GetType() == TILE_STAIRS_TOP));
}

int World::GetTileValue(int x, int y) {
  if (!IsTileIndexInBounds(x, y, map_width, map_height)) {
    return empty_tile.GetValue();
  }
  return world_tiles[x][y]->GetValue();
}

int World::GetTileValueByCoord(int x, int y)
{
  if (!IsWorldCoordinateInBounds(x, y, map_width, map_height,
                                 tileset_tile_width, tileset_tile_height)) {
    return empty_tile.GetValue();
  }

  int tile_x = x / tileset_tile_width;
  int tile_y = y / tileset_tile_height;

  return world_tiles[tile_x][tile_y]->GetValue();
}

Tile* World::GetTileByCoord(int x, int y)
{
  if (!IsWorldCoordinateInBounds(x, y, map_width, map_height,
                                 tileset_tile_width, tileset_tile_height)) {
    return &boundary_tile;
  }

  int tile_x = x / tileset_tile_width;
  int tile_y = y / tileset_tile_height;

  return world_tiles[tile_x][tile_y];
}

void World::WorldStep(Character* player) {

  // Perform an step of all elements belonging to the world level
  //printf("[WorldStep] Moving platforms...\n");
  for (vector<Platform*>::iterator it = platforms.begin() ; it != platforms.end(); ++it) {
      (*it)->PlatformStep();
      // REVISIT: remove this code
      //if (player->GetState() == CHAR_STATE_HITTING) {
      //  (*it)->SetTrigger();
      //}
  }

  // Back objects (no deleteable)
  //printf("[WorldStep] Moving back objects...\n");
  for (list<Object*>::iterator it = back_objects.begin() ; it != back_objects.end(); ++it) {
    Object* object = *it;
    if (object->GetActive()) {      
      switch (object->GetType()) {
        case OBJ_STATIC:
          ((StaticObject*)object)->StaticObjectStep();
          break;
        default:
          break;
      }
    }
  }

  // Remove dead blocks before stepping survivors. EraseAndDisposeIf keeps the
  // iterator returned by erase(), including when consecutive elements die.
  EraseAndDisposeIf(
      blocks,
      [](Block* block) { return block->GetState() == OBJ_STATE_DEAD; },
      [](Block* block) { delete block; });

  for (list<Block*>::iterator it = blocks.begin(); it != blocks.end(); ++it) {
    if ((*it)->GetActive()) {
      (*it)->ObjectStep(this, player);
    }
  }

  // Items, shots and bombs are the transient object types. Other object types
  // are referenced by triggers and must not be removed without unlinking them.
  EraseAndDisposeIf(
      objects,
      [](Object* object) {
        if (object->GetState() != OBJ_STATE_DEAD) {
          return false;
        }
        return object->GetType() == OBJ_ITEM ||
               object->GetType() == OBJ_SHOOT ||
               object->GetType() == OBJ_BOMB;
      },
      [this](Object* object) {
        if (object->GetType() == OBJ_SHOOT) {
          shoot_exists = false;
        } else if (object->GetType() == OBJ_BOMB) {
          bomb_exists = false;
        }
        delete object;
      });

  // Step surviving global objects.
  for (list<Object*>::iterator it = objects.begin(); it != objects.end(); ++it) {
    Object* object = *it;

    // REVISIT: to trigger some events. Remove this code
    if (player->GetState() == CHAR_STATE_HITTING) {
      if (object->GetType() == OBJ_HAZARD)
        ((Hazard*)object)->SetTrigger();
    }

    if (object->GetState() == OBJ_STATE_DEAD) {
      printf("[WARNING] Persistent object %d reached the dead state and was not removed\n",
             object->GetId());
    } else if (object->GetActive()) {
      //printf("Object active id = %d, type = %d\n", object->GetId(), object->GetType());
      switch (object->GetType()) {
        case OBJ_ITEM:
          ((Item*)object)->ObjectStep(this, player);
          break;
        case OBJ_STATIC:
          ((StaticObject*)object)->StaticObjectStep();
          break;
        case OBJ_HAZARD:
          ((Hazard*)object)->HazardStep(this, player);
          break;
        case OBJ_LASER:
          ((Laser*)object)->ObjectStep(this, player);
          break;
        case OBJ_SHOOT:
          ((Shoot*)object)->ObjectStep(this, player);
          break;
        case OBJ_BOMB:
          ((Bomb*)object)->ObjectStep(this, player);
          break;
        default:
          break;
      }
    } else {
      printf("Object inactive %d\n", object->GetId());
    }
  }

  // Handle checkpoints
  //printf("[WorldStep] Handling checkpoints...\n");
  if (player->GetState() != CHAR_STATE_DYING) {
    for (vector<Checkpoint*>::iterator it = target_checkpoints->begin(); it != target_checkpoints->end(); it++) {
      Checkpoint* checkpoint = *it;
      if (checkpoint->InCheckpoint(player->GetPosX(), player->GetPosY(),
                                   player->GetWidth(), player->GetHeight())) {
        // player is in a target checkpoint. Move the current_checkpoint.
        current_checkpoint = checkpoint;
        // re-compute target_checkpoints
        target_checkpoints = current_checkpoint->GetNextCheckpoints();
        break;
      }
    }
  }

  // Handle triggers
  for (list<Trigger*>:: iterator it = triggers.begin(); it != triggers.end(); it++) {
    Trigger* trigger = *it;
    trigger->TriggerStep(player->GetPosX(), player->GetPosY(),
                         player->GetWidth(), player->GetHeight(),
                         player->GetDirection(), player->GetState());
  }

  // Handle enemies
  //printf("[WorldStep] Handling enemies...\n");
  for (vector<Character*>::iterator it = enemies.begin(); it != enemies.end(); it++) {
    Enemy* enemy = (Enemy*)*it;
    enemy->CharacterStep(this, player);
  }

  // Check if player has been killed in this step
  // REVISIT: this check can be done at the begginning of this function and avoid
  // traversing some of the list. Triggers for instance is traversed two times.
  if (player->GetKilled()) {
    printf("[WorldStep] Player killed!\n");
    // If player got killed, then reset the triggers
    for (list<Trigger*>:: iterator it = triggers.begin(); it != triggers.end(); it++) {
      Trigger* trigger = *it;
      trigger->Reset();
    }
    // Traverse some objects to reset them if required
    for (list<Object*>::iterator it = objects.begin() ; it != objects.end(); ++it) {
      Object* object = *it;
      if (object->GetType() == OBJ_LASER)
        ((Laser*)object)->Reset();
    }
  }

  //printf("[WorldStep] Completed!\n");  
}

bool World::CreateNewShoot(int x, int y, int direction) {
  bool created = false;
  // Allow only one shoot to be created right now
  if (!shoot_exists) {
    const nlohmann::json& config = GetProjectileDefinition("shoot");
    Shoot* shoot = new Shoot(config.at("definition").get<std::string>().c_str(),
                             x, y + config.at("yOffset").get<int>(),
                             config.at("width").get<int>(),
                             config.at("height").get<int>(), direction);
    objects.push_back(shoot);
    shoot_exists = true;
    created = true;
  }

  return created;
}

bool World::CreateNewBomb(int x, int y, int direction) {
  bool created = false;
  // Allow only one bomb to be created right now
  if (!bomb_exists) {    
    printf("CreateNewBomb x=%d, y=%d\n", x, y);
    const nlohmann::json& config = GetProjectileDefinition("bomb");
    Bomb* shoot = new Bomb(config.at("definition").get<std::string>().c_str(),
                           x, y + config.at("yOffset").get<int>(),
                           config.at("width").get<int>(),
                           config.at("height").get<int>(), direction);
    if (config.contains("boundingBox")) {
      const nlohmann::json& box = config.at("boundingBox");
      shoot->SetBoundingBox(box.at("x").get<int>(), box.at("y").get<int>(),
                            box.at("width").get<int>(),
                            box.at("height").get<int>());
    }
    objects.push_back(shoot);
    bomb_exists = true;
    created = true;
  }

  return created;
}

Platform* World::GetPlatform(int id) {
  for (vector<Platform*>::iterator it = platforms.begin() ; it != platforms.end(); ++it) {
    Platform* platform = *it;
    if (platform->GetTypeId() == id)
      return platform;
  }

  return nullptr;
}

Hazard* World::GetHazard(int id) {
  for (list<Object*>::iterator it = objects.begin() ; it != objects.end(); ++it) {
    Object* object = *it;

    if ((object->GetType() == OBJ_HAZARD) && (object->GetTypeId() == id))
      return (Hazard*)object;
  }

  return nullptr;
}

Laser* World::GetLaser(int id) {
  for (list<Object*>::iterator it = objects.begin() ; it != objects.end(); ++it) {
    Object* object = *it;

    if ((object->GetType() == OBJ_LASER) && (object->GetTypeId() == id))
      return (Laser*)object;
  }

  return nullptr;
}

CameraView* World::GetCurrentCameraView(Character* player) {
  int player_x;
  int player_y;
  int player_dir;
  CameraView* view;

  // REVISIT: at the moment, camera views are not taking into account vertical movements
  player_dir = player->GetFace();
  player_x   = player->GetPosX() + ((player_dir == CHAR_DIR_RIGHT) ? player->GetWidth() : 0);
  player_y   = player->GetPosY();

  view = nullptr;
  for (vector<CameraView*>::iterator it = camera_views.begin(); it != camera_views.end(); it++) {
    CameraView* view_to_analyze = *it;

    if( (player_x >= view_to_analyze->GetLeftUpX())   &&
        (player_x < view_to_analyze->GetRightDownX()) &&
        (player_y >= view_to_analyze->GetLeftUpY())   &&
        (player_y < view_to_analyze->GetRightDownY())) {
      if(!view) {
        view = view_to_analyze;
      } else {
        if (player_dir & CHAR_DIR_RIGHT) {
          if (view_to_analyze->GetLeftUpX() > view->GetLeftUpX())
            view = view_to_analyze;
        } else if (player_dir & CHAR_DIR_LEFT) {
          if (view_to_analyze->GetLeftUpX() < view->GetLeftUpX())
            view = view_to_analyze;
        }
      }
    }
  }

  return view;
}
